import {test} from 'node:test';import assert from 'node:assert/strict';
import {createConfigurationRecoveryAdapter} from '../src/host/configurationRecovery.ts';
const route={id:'codex:discovered:synthetic',kind:'codex',executablePath:'/synthetic/codex',installed:true};
const snapshot={schemaVersion:1,activeConversationID:'chat',selectedProviderID:null,providers:[],runs:[],conversations:[{id:'chat',title:'Saved',readOnly:false,draft:'Keep',richDraft:{schemaVersion:1,revision:0,attachmentIDs:[],selection:null,team:null}}]};
const copy=v=>structuredClone(v);
function fixture(){let op=null,sequence=0,applications=0;const calls=[];const bridge={async reserveProviderConfiguration(intent){calls.push('reserve');if(op&&!op.acknowledged)throw Error('pending');op={schemaVersion:1,operationID:`configuration:${++sequence}`,intent:copy(intent),state:'reserved',acknowledged:false};return copy(op);},async getProviderConfigurationOperation(){calls.push('read');return op&&!op.acknowledged?copy(op):null;},async applyProviderConfiguration(intent,id){calls.push('apply');assert.equal(id,op.operationID);assert.deepEqual(intent,op.intent);op.state='applied';applications++;return copy(op);},async reconcileProviderConfiguration(id){calls.push('reconcile');assert.equal(id,op.operationID);if(op.state==='reserved')op.state='rejected';return copy(op);},async acknowledgeProviderConfiguration(id){calls.push('ack');assert.equal(id,op.operationID);op.acknowledged=true;return copy(op);}};return {bridge,calls,get op(){return op},get applications(){return applications}};}
test('lost apply acknowledgement is recovered after adapter restart without replay',async()=>{const f=fixture();const apply=f.bridge.applyProviderConfiguration;f.bridge.applyProviderConfiguration=async(...args)=>{await apply(...args);throw Error('lost')};assert.equal((await createConfigurationRecoveryAdapter(f.bridge).configure(route,snapshot,true)).state,'uncertain');const fresh=createConfigurationRecoveryAdapter(f.bridge);assert.equal((await fresh.read()).state,'applied');assert.equal(f.applications,1);assert.equal(await fresh.reconcile(),'applied');assert.equal(await fresh.read(),null);assert.equal(f.applications,1);assert.deepEqual(f.calls,['reserve','apply','read','read','reconcile','ack','read']);});
test('lost reservation reply survives restart and closes without applying',async()=>{const f=fixture();const reserve=f.bridge.reserveProviderConfiguration;f.bridge.reserveProviderConfiguration=async i=>{await reserve(i);throw Error('lost')};assert.equal((await createConfigurationRecoveryAdapter(f.bridge).configure(route,snapshot,true)).state,'uncertain');const fresh=createConfigurationRecoveryAdapter(f.bridge);assert.equal((await fresh.read()).state,'reserved');assert.equal(await fresh.reconcile(),'rejected');assert.equal(f.applications,0);});
test('mismatched ID or payload and failed durability acknowledgement stay uncertain',async()=>{for(const field of ['operationID','intent','ack']){const f=fixture();const apply=f.bridge.applyProviderConfiguration;f.bridge.applyProviderConfiguration=async(...a)=>{const result=await apply(...a);if(field==='operationID')result.operationID='configuration:999';if(field==='intent')result.intent.select=false;return result;};if(field==='ack')f.bridge.acknowledgeProviderConfiguration=async()=>{throw Error('disk')};assert.equal((await createConfigurationRecoveryAdapter(f.bridge).configure(route,snapshot,true)).state,'uncertain');assert.equal(f.op.acknowledged,false);}});
test('success and incomplete capability retain explicit boundaries',async()=>{const f=fixture();assert.equal((await createConfigurationRecoveryAdapter(f.bridge).configure(route,snapshot,true)).state,'durable');assert.equal(f.op.acknowledged,true);assert.equal(f.applications,1);assert.equal(createConfigurationRecoveryAdapter({configureSelectedProvider(){throw Error('legacy')} }),null);});
