import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {parseArtifactRequest,parseArtifactInspection,parseHostSnapshot} from './snapshot/prototypes/ai-native-workspace/src/host/contracts.ts';
import {createTauriWorkspaceAdapter} from './snapshot/prototypes/ai-native-workspace/src/host/tauriAdapter.ts';
const hash=s=>createHash('sha256').update(s).digest('hex');const text='Exact 🪐 é\n<script>literal</script>';
const q={artifactID:'artifact-a',conversationID:'chat-a',requestID:'run-a',expectedSHA256:hash(text)};
const reply=(txt=text)=>({schemaVersion:1,artifactID:q.artifactID,conversationID:q.conversationID,requestID:q.requestID,previewKind:'plainText',languageHint:null,byteLength:Buffer.byteLength(txt),contentSHA256:hash(txt),availability:'available',text:txt});
const summary=()=>({schemaVersion:1,artifactID:q.artifactID,conversationID:q.conversationID,requestID:q.requestID,origin:{kind:'finalAnswer',memberID:null,providerID:'codex'},displayName:'Final answer',previewKind:'plainText',languageHint:null,byteLength:Buffer.byteLength(text),contentSHA256:hash(text),availability:'available',createdAt:'2026-09-10',supersedesArtifactID:null});
function snapshot(){const provider={id:'codex',kind:'codex',executablePath:'/synthetic/codex',model:null,timeoutMs:60000};return {schemaVersion:1,activeConversationID:'chat-a',selectedProviderID:'codex',providers:[provider],conversations:['chat-a','chat-b'].map(id=>({id,title:id,readOnly:false,draft:'',richDraft:{schemaVersion:1,revision:0,attachmentIDs:[],selection:null,team:null}})),runs:[{id:'run-a',conversationID:'chat-a',status:'completed',updatedAt:'now',admitted:{requestID:'run-a',conversationID:'chat-a',prompt:'Synthetic',mode:'direct',provider,retryOf:null},answer:text,error:null}],artifacts:[summary()]};}
for(const field of ['artifactID','conversationID','requestID','expectedSHA256'])test(`reject bridge-mutated ${field} after await; caller identity unchanged`,async()=>{
 const bridge=Object.fromEntries(['getSnapshot','getModelCatalog','createConversation','openConversation','saveRichDraft','submitRun','reconcileRun','cancelRun','onRunEvent'].map(k=>[k,async()=>{}]));let calls=0;
 bridge.inspectArtifact=async request=>{calls++;await Promise.resolve();request[field]=field==='expectedSHA256'?hash('different'):'other';const result=reply(field==='expectedSHA256'?'different':text);if(field!=='expectedSHA256')result[field]=request[field];return result;};const before=structuredClone(q);await assert.rejects(createTauriWorkspaceAdapter(bridge).inspectArtifact(q));assert.deepEqual(q,before);assert.equal(calls,1);
});
test('lone and malformed surrogate sequences reject replacement-byte hashes',async()=>{for(const invalid of ['\ud800','\udc00','x\ud800y','\ud800\ud800','\udc00\ud800'])await assert.rejects(parseArtifactInspection(reply(invalid),{...q,expectedSHA256:hash(invalid)}));});
test('valid pairs BOM combining whitespace and literal replacement character stay exact',async()=>{for(const valid of ['🪐','e\u0301','\ufeffstart','\ufffd',' \n\t🪐\r\n','']){const result=await parseArtifactInspection(reply(valid),{...q,expectedSHA256:hash(valid)});assert.equal(result.text,valid);assert.equal(result.byteLength,Buffer.byteLength(valid));}});
