const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {chromium}=require('/Users/Aaravshah/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=process.env.RIVUNE_RENDERER_EVIDENCE_DIR || fs.mkdtempSync(path.join(require('os').tmpdir(),'rivune-r2-renderer-'));
fs.mkdirSync(root,{recursive:true});
const web=path.resolve(__dirname,'../web');
(async()=>{
 const browser=await chromium.launch({executablePath:'/Users/Aaravshah/Library/Caches/ms-playwright/chromium_headless_shell-1223/chrome-headless-shell-mac-arm64/chrome-headless-shell',headless:true});
 const results=[],errors=[];const check=(name,result)=>{assert.ok(result,name);results.push({name,pass:true})};
 async function setup(options={}){
  const ctx=await browser.newContext({viewport:{width:1120,height:760},reducedMotion:'reduce'});
  await ctx.route('https://rivune-integrated.test/**',async route=>{const name=new URL(route.request().url()).pathname.slice(1)||'index.html',file=path.resolve(web,name);if(!file.startsWith(web+path.sep)||!fs.existsSync(file))return route.abort();const types={'.mjs':'text/javascript','.js':'text/javascript','.css':'text/css','.html':'text/html','.png':'image/png','.svg':'image/svg+xml'};await route.fulfill({body:fs.readFileSync(file),contentType:types[path.extname(file)]||'text/plain'})});
  const page=await ctx.newPage();page.on('pageerror',e=>errors.push(String(e)));
  await page.addInitScript(options=>{
   window.__polls=[];window.setInterval=cb=>{window.__polls.push(cb);return 1};
   const provider={id:'fixture:local',kind:'fixture',executablePath:'/fixture-only',model:null,timeoutMs:1000};
   const importFingerprint='a'.repeat(64);
   const state={schemaVersion:1,activeConversationID:options.activeConversationID??'c1',selectedProviderID:options.noProvider?null:provider.id,providers:[provider],conversations:[{id:'c1',title:'Reading workshop',draft:''},{id:'c2',title:'Website ideas',draft:options.secondDraft??''}],legacyImports:[],runs:[]};
   if(options.failedRun)state.runs.push({id:'failed-source',conversationID:'c1',status:'failed',updatedAt:'2026-09-07',admitted:{requestID:'failed-source',conversationID:'c1',prompt:'original',mode:'direct',provider,approvedContext:{},retryOf:null},answer:null,error:'fixture failed'});
   const ctl=window.testHost={state,calls:[],failSave:!!options.failSave,failSnapshot:false,blockSave:false,saves:[],blockSnapshot:false,snapshots:[],blockSubmit:false,submits:[],blockRetry:false,retries:[],blockReconcile:false,reconciles:[],blockImportPreview:false,importPreviews:[],retryAck:options.retryAck??null,reconcileAck:null,failCreate:false,failCompleteShutdown:!!options.failCompleteShutdown,shutdownHandler:null,shutdownPromise:null};
   window.__RIVUNE_DESKTOP_HOST__={
    getSnapshot:async()=>{if(ctl.failSnapshot)throw Error('Fixture disconnected');const value=structuredClone(state);if(ctl.snapshotDelay)await new Promise(resolve=>setTimeout(resolve,ctl.snapshotDelay));if(ctl.blockSnapshot)await new Promise((resolve,reject)=>ctl.snapshots.push({resolve,reject}));return value},
    discoverProviders:async()=>{ctl.calls.push(['discover']);return structuredClone(options.discoveredProviders??[])},
    openConversation:async id=>{ctl.calls.push(['open',id]);state.activeConversationID=id},
    createConversation:async c=>{if(ctl.failCreate)throw Error('fixture create failed');state.conversations.push({...c,draft:''})},
    configureProvider:async p=>{if(p.executablePath==='/bad')throw Error('Fixture invalid provider');state.selectedProviderID=p.id;ctl.calls.push(['configure',p])},
    saveRichDraft:async request=>{const {conversationID:id,draft}=request;ctl.calls.push(['save-start',id,draft]);if(ctl.failSave)throw Error('permission denied fixture');if(ctl.blockSave)await new Promise(resolve=>ctl.saves.push(resolve));state.conversations.find(c=>c.id===id).draft=draft;ctl.calls.push(['save-done',id,draft]);state.conversations.find(c=>c.id===id).richDraft={schemaVersion:1,revision:request.expectedRevision+1,attachmentIDs:request.attachmentIDs,selection:request.selection,team:request.team};return {state:'durable',mutationID:request.mutationID,conversationID:id,revision:request.expectedRevision+1,attachmentIDs:request.attachmentIDs,selection:request.selection,team:request.team}},
    previewLegacyImport:async sources=>{ctl.calls.push(['import-preview',sources]);if(ctl.blockImportPreview)await new Promise(resolve=>ctl.importPreviews.push(resolve));return {fingerprint:importFingerprint,reviewable:true,conversationCount:1,turnCount:1,projectCount:1,draftCount:1,sourceCount:sources.length,answerCount:1,attachmentCount:0,activatedDraftCount:1,archiveOnlyDraftCount:0,preferencesPreserved:sources.some(s=>s.kind==='preferences'),issues:[{source:'history',code:'legacy-exact-retry-unavailable',field:'/0/turns/0',blocking:false}]}},
    commitLegacyImport:async fingerprint=>{ctl.calls.push(['import-commit',fingerprint]);const receipt={fingerprint,conversationCount:1,turnCount:1,projectCount:1,draftCount:1,sourceCount:1,answerCount:1,attachmentCount:0,activatedDraftCount:1,archiveOnlyDraftCount:0,preferencesPreserved:false,safetyNoticeCount:1};state.legacyImports.push(receipt);state.conversations.push({id:'legacy:fixture:c3',title:'Imported work',draft:'preserved',readOnly:true});state.activeConversationID='legacy:fixture:c3';state.runs.push({id:'legacy-run:fixture',conversationID:'legacy:fixture:c3',status:'completed',updatedAt:'1',admitted:{requestID:'legacy-run:fixture',conversationID:'legacy:fixture:c3',prompt:'Legacy question',mode:'imported-read-only',provider:{id:'imported:legacy',kind:'imported',executablePath:'',model:null,timeoutMs:1000},approvedContext:{},retryOf:null},answer:'Legacy answer',error:null});return {fingerprint,conversationCount:1,state:'imported',receipt}},
    recoverLegacyImport:async fingerprint=>{ctl.calls.push(['import-recover',fingerprint]);return [{kind:'history',filename:'rivune-legacy-fixture-history.json',sha256:'fixture',bytes:[91,93]}]},
    exportLegacyImport:async fingerprint=>{ctl.calls.push(['import-export',fingerprint]);return structuredClone(options.exportReceipt??{platform:'macOS',saved:[{filename:'rivune-legacy-fixture-history.json',sha256:'b'.repeat(64),bytes:2}],cancelled:false,error:null,uncertainFilename:null})},
    inspectLegacyImport:async fingerprint=>{ctl.calls.push(['import-inspect',fingerprint]);return {schemaVersion:1,fingerprint,sections:[{kind:'projects',items:[{id:'projects:1',label:'Saved project',detailText:'Availability: Archived only'}],totalCount:1,truncated:false},{kind:'orphanDrafts',items:[],totalCount:0,truncated:false},{kind:'attachments',items:[],totalCount:0,truncated:false},{kind:'preferences',items:[],totalCount:0,truncated:false},{kind:'notices',items:[],totalCount:0,truncated:false}]}},
    submitRun:async r=>{ctl.calls.push(['submit',r]);state.runs.push({id:r.id,conversationID:r.conversationID,status:'running',updatedAt:'2026-09-07',admitted:{requestID:r.id,conversationID:r.conversationID,prompt:r.prompt,mode:r.mode,provider,approvedContext:{},retryOf:null},answer:null,error:null});if(ctl.blockSubmit)await new Promise(resolve=>ctl.submits.push(resolve));return {state:'accepted',requestID:r.id}},
    reconcileRun:async id=>{ctl.calls.push(['reconcile',id]);if(ctl.blockReconcile)await new Promise(resolve=>ctl.reconciles.push(resolve));return ctl.reconcileAck?{...ctl.reconcileAck,requestID:id}:{state:'accepted',requestID:id}},
    cancelRun:async id=>{state.runs.find(r=>r.id===id).status='cancelled';return {state:'accepted',requestID:id}},
    retryRun:async(a,b)=>{ctl.calls.push(['retry',a,b]);if(ctl.blockRetry)await new Promise(resolve=>ctl.retries.push(resolve));return ctl.retryAck??{state:'accepted',requestID:b}}
    ,onShutdownRequested:handler=>{ctl.shutdownHandler=handler},
    beginShutdown:async token=>{ctl.calls.push(['shutdown-begin',token])},
    flushShutdownDraft:async r=>{const {token,conversationID,draft,clientRevision}=r;ctl.calls.push(['shutdown-flush',token,conversationID,draft,clientRevision]);return {state:'durable',token,clientRevision,mutationID:r.mutationID,conversationID,richDraftRevision:conversationID===null?null:r.expectedRichRevision+1,attachmentIDs:r.attachmentIDs,selection:r.selection,team:r.team}},
    completeShutdown:async token=>{ctl.calls.push(['shutdown-complete',token]);if(ctl.failCompleteShutdown)throw Error('fixture final save failed')},
    abortShutdown:async token=>{ctl.calls.push(['shutdown-abort',token])}
   };
  },options);
  await page.goto('https://rivune-integrated.test/',{waitUntil:'networkidle'});return {page,ctx};
 }
 const tick=async p=>{await p.evaluate(()=>window.__polls.forEach(f=>f()));await p.waitForTimeout(15)};
 try{
  {const {page:p,ctx}=await setup({failSave:true});await p.locator('#prompt').fill('Keep this unsaved work');await p.waitForTimeout(220);await p.evaluate(()=>testHost.failSnapshot=true);await tick(p);await p.evaluate(()=>testHost.failSnapshot=false);await tick(p);check('failed save plus reconnect preserves unsaved text',await p.locator('#prompt').inputValue()==='Keep this unsaved work');await p.locator('#conversations button').nth(1).click();await p.locator('#prompt').fill('Separate B draft');await p.locator('#conversations button').first().click();check('failed save plus navigation retains each local draft',await p.locator('#prompt').inputValue()==='Keep this unsaved work');check('save warning remains pinned through polling',(await p.locator('#connection-status').textContent()).includes('couldn’t save'));await ctx.close()}
  {const {page:p,ctx}=await setup();await p.locator('#prompt').fill('Send only once');await p.locator('#submit').click();await p.waitForTimeout(230);check('accepted send cancels stale draft debounce',await p.evaluate(()=>testHost.state.conversations[0].draft==='')&&await p.locator('#prompt').inputValue()==='');await p.evaluate(()=>{testHost.state.runs[0].status='completed';testHost.state.runs[0].answer='# A good first session\n\nTry **one short story** and compare perspectives.\n\n```js\nconst idea = "Read together";\n```'});await tick(p);check('asynchronous completion renders full prompt and formatted answer',await p.locator('.user-message').textContent()==='Send only once'&&await p.locator('.markdown h2').textContent()==='A good first session');check('no unsupported copy or external-opener controls',await p.locator('.code-header button,.markdown [role=link]').count()===0);await p.locator('#conversations button').first().focus();await tick(p);check('poll preserves sidebar focus',await p.evaluate(()=>document.activeElement.matches('#conversations button')));await p.screenshot({path:path.join(root,'integrated-desktop.png')});await ctx.close()}
  {const {page:p,ctx}=await setup();await p.locator('#prompt').fill('Keep latest stored draft');await p.waitForTimeout(210);await p.locator('#conversations button').nth(1).click();await p.locator('#conversations button').first().click();check('navigation reads latest saved draft',await p.locator('#prompt').inputValue()==='Keep latest stored draft');await ctx.close()}
  {const {page:p,ctx}=await setup();await p.evaluate(()=>testHost.blockSave=true);await p.locator('#prompt').fill('One request during slow save');await p.evaluate(()=>{const form=document.querySelector('#prompt-form');form.dispatchEvent(new Event('submit',{cancelable:true}));form.dispatchEvent(new Event('submit',{cancelable:true}))});await p.waitForTimeout(15);check('slow pre-submit save admits one handler',await p.evaluate(()=>testHost.saves.length===1));await p.evaluate(()=>{testHost.blockSave=false;testHost.saves.shift()()});await p.waitForTimeout(25);check('slow save double-submit reaches host once',await p.evaluate(()=>testHost.calls.filter(c=>c[0]==='submit').length===1));await ctx.close()}
  {const {page:p,ctx}=await setup({failSave:true});await p.locator('#prompt').fill('Preserve on save rejection');await p.waitForTimeout(220);check('save failure keeps Send disabled',await p.locator('#submit').isDisabled());await p.evaluate(()=>document.querySelector('#prompt-form').dispatchEvent(new Event('submit',{cancelable:true})));await p.waitForTimeout(20);check('submit save rejection preserves draft without dispatch',await p.locator('#prompt').inputValue()==='Preserve on save rejection'&&await p.evaluate(()=>!testHost.calls.some(c=>c[0]==='submit')));await ctx.close()}
  {const {page:p,ctx}=await setup();await p.locator('#prompt').fill('A draft');await p.evaluate(()=>testHost.blockSnapshot=true);await p.locator('#conversations button').nth(1).click();await p.waitForTimeout(15);await tick(p);check('polling is suppressed during navigation',await p.evaluate(()=>testHost.snapshots.length===1));await p.locator('#prompt').fill('A edited during navigation');await p.evaluate(()=>{testHost.blockSnapshot=false;testHost.snapshots.shift().resolve()});await p.waitForTimeout(25);check('navigation atomically switches ID and displayed draft',await p.locator('#prompt').inputValue()==='');await p.locator('#conversations button').first().click();check('typing during navigation stays with source conversation',await p.locator('#prompt').inputValue()==='A edited during navigation');check('destination draft is not contaminated',await p.evaluate(()=>testHost.state.conversations[1].draft===''));await ctx.close()}
  {const {page:p,ctx}=await setup();await p.evaluate(()=>testHost.blockSnapshot=true);await tick(p);await p.evaluate(()=>testHost.blockSnapshot=false);await p.locator('#conversations button').nth(1).click();await p.locator('#prompt').fill('B remains selected');await p.evaluate(()=>testHost.snapshots.shift().reject(Error('Old failed poll')));await p.waitForTimeout(25);check('old failed poll cannot undo later navigation',await p.locator('#prompt').inputValue()==='B remains selected'&&await p.locator('#conversations button').nth(1).getAttribute('aria-pressed')==='true');await ctx.close()}
  {const {page:p,ctx}=await setup();await p.evaluate(()=>testHost.blockSubmit=true);await p.locator('#prompt').fill('Submitted A');await p.locator('#submit').click();await p.waitForTimeout(15);await p.locator('#conversations button').nth(1).click();await p.locator('#prompt').fill('Unsaved B');await p.evaluate(()=>testHost.submits.shift()());await p.waitForTimeout(25);check('late A acknowledgment leaves B draft intact',await p.locator('#prompt').inputValue()==='Unsaved B');await p.locator('#conversations button').first().click();check('late acknowledgment clears unchanged submitted A draft',await p.locator('#prompt').inputValue()==='');await ctx.close()}
  {const {page:p,ctx}=await setup();await p.evaluate(()=>testHost.blockSubmit=true);await p.locator('#prompt').fill('Old request');await p.locator('#submit').click();await p.waitForTimeout(15);await p.locator('#prompt').fill('New draft during response');await p.evaluate(()=>testHost.submits.shift()());await p.waitForTimeout(25);check('new draft survives old request acknowledgment',await p.locator('#prompt').inputValue()==='New draft during response');await ctx.close()}
  {const {page:p,ctx}=await setup({noProvider:true});check('missing provider disables send',await p.locator('#submit').isDisabled());check('missing provider is not reported as connected',(await p.locator('#connection-status').textContent()).includes('Choose an AI'));await p.locator('#prompt').fill('Settings preserves this');await p.keyboard.press('Control+,');check('settings is an in-app modal',await p.locator('#settings-dialog').evaluate(n=>n.matches(':modal')));await p.keyboard.press('Escape');check('settings restores composer focus and text',await p.evaluate(()=>document.activeElement.id==='prompt')&&await p.locator('#prompt').inputValue()==='Settings preserves this');await p.locator('#open-settings').click();await p.locator('#settings-tab-connections').click();await p.locator('#provider-advanced summary').click();await p.locator('[data-provider="claude"]').click();await p.locator('#provider-path').fill('/fixture/bin/claude');await p.locator('#connect-provider').click();check('provider selection uses real existing configure handler',await p.evaluate(()=>testHost.calls.some(c=>c[0]==='configure'&&c[1].kind==='claude')));await p.screenshot({path:path.join(root,'integrated-settings.png')});await p.keyboard.press('Escape');for(const [width,height] of [[760,560],[390,844]]){await p.setViewportSize({width,height});check(`integrated layout has no horizontal overflow ${width}`,await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:path.join(root,`integrated-${width}.png`)})}await ctx.close()}
  {const {page:p,ctx}=await setup({noProvider:true,discoveredProviders:[{id:'codex:detected-fixture',kind:'codex',displayName:'Untrusted name',executablePath:'/fixture/bin/codex',installed:true,authentication:'unknown',tested:false}]});await p.locator('#open-settings').click();await p.locator('#settings-tab-connections').click();await p.locator('.detected-provider').waitFor();check('detection truthfully separates install auth and response state',(await p.locator('.detected-provider').textContent()).includes('CodexInstalled · Sign-in not checked · Response not tested'));check('discovery runs without configuring or sending a provider request',await p.evaluate(()=>testHost.calls.filter(c=>c[0]==='discover').length>=1&&!testHost.calls.some(c=>c[0]==='configure'||c[0]==='submit')));await p.getByRole('button',{name:'Set up Codex'}).click();check('detected provider only stages the exact executable path',await p.locator('#provider-path').inputValue()==='/fixture/bin/codex'&&await p.evaluate(()=>!testHost.calls.some(c=>c[0]==='configure')));await p.locator('#connect-provider').click();check('explicit Save configures the staged detected provider',await p.evaluate(()=>testHost.calls.some(c=>c[0]==='configure'&&c[1].kind==='codex'&&c[1].executablePath==='/fixture/bin/codex')));await ctx.close()}
  {const {page:p,ctx}=await setup({failSave:true});await p.evaluate(()=>{const field=document.querySelector('#prompt');field.value='x'.repeat(128*1024+1);field.dispatchEvent(new Event('input',{bubbles:true}))});await p.waitForTimeout(220);await p.locator('#conversations button').nth(1).click();await p.waitForTimeout(25);await p.evaluate(()=>{testHost.shutdownPromise=Promise.resolve(testHost.shutdownHandler('shutdown-oversized'))});await p.evaluate(()=>testHost.shutdownPromise);check('oversized offscreen draft stops quit before the workspace freezes',await p.evaluate(()=>!document.querySelector('.shell').inert&&!testHost.calls.some(c=>c[0]==='shutdown-begin'))&&!await p.locator('#prompt').isDisabled()&&(await p.locator('#connection-status').textContent()).includes('128 KB local limit'));await p.locator('#conversations button').first().click();check('oversized draft remains editable and recoverable in its original conversation',await p.locator('#prompt').isEditable()&&await p.locator('#prompt').evaluate(field=>field.value.length===128*1024+1));await ctx.close()}
  {const {page:p,ctx}=await setup();await p.evaluate(()=>testHost.blockSave=true);await p.locator('#prompt').fill('older pending draft');await p.waitForTimeout(210);await p.locator('#prompt').fill('latest draft before quit');await p.evaluate(()=>{testHost.shutdownPromise=Promise.resolve(testHost.shutdownHandler('shutdown-fixture'))});check('shutdown immediately freezes ordinary workspace interaction',await p.locator('.shell').evaluate(node=>node.inert)&&await p.locator('#prompt').isDisabled()&&await p.locator('#new-conversation').isDisabled());await p.evaluate(()=>{testHost.blockSave=false;testHost.saves.shift()()});await p.evaluate(()=>testHost.shutdownPromise);check('shutdown flushes and acknowledges the latest frozen draft before completion',await p.evaluate(()=>{const flush=testHost.calls.find(c=>c[0]==='shutdown-flush');const complete=testHost.calls.find(c=>c[0]==='shutdown-complete');return flush?.[1]==='shutdown-fixture'&&flush?.[2]==='c1'&&flush?.[3]==='latest draft before quit'&&Number.isInteger(flush?.[4])&&complete?.[1]==='shutdown-fixture'&&testHost.calls.indexOf(flush)<testHost.calls.indexOf(complete)}));await ctx.close()}
  {const {page:p,ctx}=await setup({failCompleteShutdown:true});await p.locator('#prompt').fill('keep me after failed quit');await p.evaluate(()=>{testHost.shutdownPromise=Promise.resolve(testHost.shutdownHandler('shutdown-failure'))});await p.evaluate(()=>testHost.shutdownPromise);check('failed final save keeps the workspace frozen and does not auto-recover',await p.evaluate(()=>!testHost.calls.some(c=>c[0]==='shutdown-abort')&&testHost.calls.filter(c=>c[0]==='shutdown-complete').length===1)&&await p.locator('.shell').evaluate(node=>node.inert)&&(await p.locator('#connection-status').textContent()).includes('Quit again'));await p.evaluate(()=>{testHost.failCompleteShutdown=false;testHost.shutdownPromise=Promise.resolve(testHost.shutdownHandler('shutdown-failure'))});await p.evaluate(()=>testHost.shutdownPromise);check('same quit token retries the verified save without reopening mutations',await p.evaluate(()=>testHost.calls.filter(c=>c[0]==='shutdown-begin'&&c[1]==='shutdown-failure').length===2&&testHost.calls.filter(c=>c[0]==='shutdown-complete'&&c[1]==='shutdown-failure').length===2&&!testHost.calls.some(c=>c[0]==='shutdown-abort')));await ctx.close()}
  {const {page:p,ctx}=await setup({failSave:true});await p.locator('#prompt').fill('dirty draft A');await p.waitForTimeout(210);await p.locator('#conversations button').nth(1).click();await p.locator('#prompt').fill('dirty draft B');await p.waitForTimeout(210);await p.evaluate(()=>{testHost.shutdownPromise=Promise.resolve(testHost.shutdownHandler('shutdown-multiple'))});await p.evaluate(()=>testHost.shutdownPromise);check('unresolved offscreen draft saves keep recovery accessible before shutdown',await p.locator('.shell').evaluate(e=>!e.inert)&&await p.evaluate(()=>!testHost.calls.some(c=>c[0]==='shutdown-begin')));await p.evaluate(()=>testHost.failSave=false);await p.locator('#retry-draft-save').click();await p.waitForTimeout(40);await p.locator('#conversations button').first().click();await p.locator('#retry-draft-save').click();await p.waitForTimeout(40);await p.evaluate(()=>{testHost.shutdownPromise=Promise.resolve(testHost.shutdownHandler('shutdown-multiple'))});await p.evaluate(()=>testHost.shutdownPromise);check('recovered offscreen and current drafts are durable before shutdown completes',await p.evaluate(()=>{const calls=testHost.calls;const complete=calls.findIndex(c=>c[0]==='shutdown-complete');return complete>0&&['c1','c2'].every(id=>calls.slice(0,complete).some(c=>c[0]==='save-done'&&c[1]===id&&c[2]===('dirty draft '+(id==='c1'?'A':'B'))))}));await ctx.close()}
  {for(const failCompleteShutdown of [false,true]){const {page:p,ctx}=await setup({failedRun:true,failCompleteShutdown});await p.evaluate(()=>testHost.blockRetry=true);await p.locator('#retry-run').click();await p.waitForTimeout(15);await p.evaluate(()=>{testHost.retryAck={};testHost.blockRetry=false;testHost.retries.shift()()});await p.waitForTimeout(20);await p.evaluate(()=>testHost.blockReconcile=true);await p.locator('#reconcile').click();await p.waitForFunction(()=>testHost.reconciles.length===1);await p.evaluate(failed=>{testHost.shutdownPromise=Promise.resolve(testHost.shutdownHandler(failed?'shutdown-late-failed':'shutdown-late-success'))},failCompleteShutdown);await p.evaluate(()=>testHost.shutdownPromise);const before=await p.evaluate(()=>testHost.calls.length);await p.evaluate(()=>{testHost.blockReconcile=false;testHost.reconciles.shift()()});await p.waitForTimeout(25);check(`late reconciliation cannot mutate after ${failCompleteShutdown?'failed':'successful'} final flush`,await p.evaluate(before=>localStorage.getItem('rivune.pending-retry.v1')!==null&&!testHost.calls.slice(before).some(c=>c[0]==='save-start'||c[0]==='shutdown-flush'),before));await ctx.close()}}
  {const {page:p,ctx}=await setup();await p.evaluate(()=>testHost.blockSave=true);await p.locator('#prompt').fill('First save');await p.waitForTimeout(210);await p.locator('#prompt').fill('Latest save');await p.waitForTimeout(210);check('per-conversation saves do not overtake each other',await p.evaluate(()=>testHost.saves.length===1));await p.evaluate(()=>{testHost.blockSave=false;testHost.saves.shift()()});await p.waitForTimeout(30);check('serialized saves retain newest stored text',await p.evaluate(()=>testHost.state.conversations[0].draft==='Latest save'));await ctx.close()}
  {const {page:p,ctx}=await setup();await p.locator('#prompt').fill('First request');await p.locator('#submit').click();await p.waitForTimeout(20);await p.evaluate(()=>{const s=testHost.state,r=s.runs[0];r.answer='Original conversation answer';r.status='completed';r.updatedAt='2099';const later=structuredClone(r);later.id='later';later.admitted.requestID='later';later.status='failed';later.error='Later request failed';later.updatedAt='1900';s.runs.push(later)});await tick(p);check('run controls follow admission order instead of completion timestamp',await p.locator('#retry-run').isVisible()&&(await p.locator('#retry-run').getAttribute('data-run-id'))==='later');await p.evaluate(()=>{const broken=structuredClone(testHost.state.runs[0]);broken.id='broken';broken.conversationID='c2';testHost.state.runs.push(broken)});await p.locator('#conversations button').nth(1).click();check('invalid destination history cannot show previous conversation as current',await p.locator('#transcript').isHidden()&&await p.locator('#submit').isDisabled()&&await p.locator('#retry-run').isHidden()&&(await p.locator('#connection-status').textContent()).includes('couldn’t read'));await ctx.close()}
  {const {page:p,ctx}=await setup();await p.evaluate(()=>{testHost.snapshotDelay=900;testHost.state.selectedProviderID=null;window.__polls.forEach(f=>f())});await p.waitForTimeout(760);await p.evaluate(()=>{testHost.state.selectedProviderID='fixture:local';window.__polls.forEach(f=>f())});await p.waitForTimeout(190);check('snapshot latency exceeding polling interval does not starve results',await p.locator('#submit').isDisabled());await p.waitForTimeout(760);check('later delayed snapshot still advances connection state',!(await p.locator('#submit').isDisabled()));await ctx.close()}
  {const {page:p,ctx}=await setup({failedRun:true});await p.evaluate(()=>testHost.blockRetry=true);await p.evaluate(()=>{const button=document.querySelector('#retry-run');button.click();button.click()});await p.waitForTimeout(15);check('retry double click reaches the host once',await p.evaluate(()=>testHost.calls.filter(c=>c[0]==='retry').length===1));check('retry is disabled while admission is pending',await p.locator('#retry-run').isDisabled());await p.evaluate(()=>{testHost.retryAck={};testHost.blockRetry=false;testHost.retries.shift()()});await p.waitForTimeout(20);const unresolved=await p.evaluate(()=>JSON.parse(localStorage.getItem('rivune.pending-retry.v1')));check('malformed retry acknowledgement preserves one retry identity',typeof unresolved?.id==='string'&&unresolved.sourceRunID==='failed-source'&&await p.locator('#reconcile').isVisible());await p.reload({waitUntil:'networkidle'});check('retry identity survives reload',await p.locator('#reconcile').isVisible());await p.evaluate(()=>testHost.reconcileAck={state:'uncertain'});await p.locator('#reconcile').click();await p.waitForTimeout(15);check('recoverable retry reconciliation keeps the same stored ID',await p.evaluate(id=>testHost.calls.filter(c=>c[0]==='reconcile'&&c[1]===id).length===1&&JSON.parse(localStorage.getItem('rivune.pending-retry.v1')).id===id,unresolved.id));await p.evaluate(()=>testHost.reconcileAck=null);await p.locator('#reconcile').click();await p.waitForTimeout(15);check('reload reconciles the same retry ID without resubmission',await p.evaluate(id=>testHost.calls.filter(c=>c[0]==='reconcile'&&c[1]===id).length===2&&!testHost.calls.some(c=>c[0]==='retry')&&localStorage.getItem('rivune.pending-retry.v1')===null,unresolved.id));await ctx.close()}
  {const {page:p,ctx}=await setup({activeConversationID:'c2',secondDraft:'reopened second draft'});check('reopen selects the host-owned active conversation',await p.locator('#conversation-title').textContent()==='Website ideas'&&await p.locator('#prompt').inputValue()==='reopened second draft'&&await p.locator('#conversations button').nth(1).getAttribute('aria-pressed')==='true');await ctx.close()}
  {const {page:p,ctx}=await setup();await p.locator('#open-settings').click();await p.evaluate(()=>{const input=document.querySelector('[data-import-kind="history"]');Object.defineProperty(input,'files',{configurable:true,value:[{size:33*1024*1024,arrayBuffer(){window.importReadCalled=true;return Promise.resolve(new ArrayBuffer(0))}}]});input.dispatchEvent(new Event('change',{bubbles:true}))});await p.locator('#preview-import').click();check('oversized legacy file is rejected before renderer reads bytes',await p.evaluate(()=>!window.importReadCalled&&!testHost.calls.some(c=>c[0]==='import-preview'))&&(await p.locator('#import-preview').textContent()).includes('Nothing was read'));await ctx.close()}
  {const {page:p,ctx}=await setup();await p.locator('#open-settings').click();await p.locator('[data-import-kind="history"]').setInputFiles({name:'conversations.json',mimeType:'application/json',buffer:Buffer.from('[]')});await p.evaluate(()=>testHost.blockImportPreview=true);await p.locator('#preview-import').click();await p.waitForFunction(()=>testHost.importPreviews.length===1);await p.evaluate(()=>document.querySelector('[data-import-kind="history"]').dispatchEvent(new Event('change',{bubbles:true})));await p.evaluate(()=>testHost.importPreviews.shift()());await p.waitForTimeout(20);check('late legacy preview cannot confirm a changed selection',await p.locator('#confirm-import').isHidden()&&(await p.locator('#import-preview').textContent()).includes('Files changed'));await ctx.close()}
  {const {page:p,ctx}=await setup();await p.locator('#open-settings').click();await p.locator('[data-import-kind="history"]').setInputFiles({name:'conversations.json',mimeType:'application/json',buffer:Buffer.from('[]')});await p.locator('#preview-import').click();await p.locator('#confirm-import').waitFor({state:'visible'});check('legacy import discloses activated versus archive-only data before confirmation',(await p.locator('#import-preview').textContent()).includes('Ready to activate 1 read-only conversation')&&(await p.locator('#import-preview').textContent()).includes('Archive only: 1 project'));check('preview sends only the explicitly selected source kind',await p.evaluate(()=>testHost.calls.find(c=>c[0]==='import-preview')[1].length===1&&testHost.calls.find(c=>c[0]==='import-preview')[1][0].kind==='history'));await p.locator('#confirm-import').click();await p.waitForFunction(()=>testHost.state.activeConversationID==='legacy:fixture:c3');check('confirmation activates the exact reviewed fingerprint once',await p.evaluate(()=>testHost.calls.filter(c=>c[0]==='import-commit'&&c[1]==='a'.repeat(64)).length===1));check('imported conversation opens read-only with preserved answer',await p.locator('#conversation-title').textContent()==='Imported work'&&await p.locator('#prompt').isDisabled()&&(await p.locator('.assistant-message').textContent()).includes('Legacy answer'));check('settings distinguishes activated and archive-only preservation',(await p.locator('#imported-data').textContent()).includes('1 read-only conversation activated')&&(await p.locator('#imported-data').textContent()).includes('archive only: 1 projects'));await p.locator('.import-inspect').click();await p.locator('.rivune-archive-inspector').waitFor({state:'visible'});check('verified archive inspection is bounded read-only UI',(await p.locator('.rivune-archive-inspector').textContent()).includes('Saved project')&&await p.evaluate(()=>testHost.calls.some(c=>c[0]==='import-inspect'&&c[1]==='a'.repeat(64))));await p.locator('.rivune-archive-inspector button[aria-label="Close archive inspection"]').click();await p.locator('.rivune-archive-inspector').waitFor({state:'hidden'});await p.locator('.import-recover').focus();await tick(p);check('polling preserves focused recovery control',await p.evaluate(()=>document.activeElement.classList.contains('import-recover')));await p.locator('.import-recover').click();check('native export reports only host-verified saved files',await p.evaluate(()=>testHost.calls.some(c=>c[0]==='import-export'&&c[1]==='a'.repeat(64)))&&(await p.locator('#connection-status').textContent()).includes('saved, synchronized, and verified by SHA-256'));check('imported provider history never exposes Retry',await p.locator('#retry-run').isHidden());await ctx.close()}
  {const {page:p,ctx}=await setup({exportReceipt:{platform:'macOS',saved:[{filename:'first.json',sha256:'c'.repeat(64),bytes:2}],cancelled:false,error:'The export folder could not be synchronized.',uncertainFilename:'second.json'}});await p.locator('#open-settings').click();await p.locator('[data-import-kind="history"]').setInputFiles({name:'conversations.json',mimeType:'application/json',buffer:Buffer.from('[]')});await p.locator('#preview-import').click();await p.locator('#confirm-import').waitFor({state:'visible'});await p.locator('#confirm-import').click();await p.waitForFunction(()=>testHost.state.activeConversationID==='legacy:fixture:c3');await p.locator('.import-recover').click();const exportStatus=await p.locator('#connection-status').textContent();check('partial native export keeps verified receipts and names the uncertain file',exportStatus.includes('1 earlier original file was saved and verified')&&exportStatus.includes('second.json may have been published but could not be fully verified')&&exportStatus.includes('Export stopped'));await ctx.close()}
  check('no unhandled renderer errors',errors.length===0);
  fs.writeFileSync(path.join(root,'INTEGRATED_BROWSER.json'),JSON.stringify({scope:'Actual R2 web modules with synthetic host, no native app/provider execution.',results,errors},null,2)+'\n');console.log(JSON.stringify({checks:results.length,errors}));
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
