// Browser-only design tour. No provider, account, storage, or network APIs.
(() => {
const $=s=>document.querySelector(s), content=$('#tour-content'), draft=$('#tour-draft');
let current='plan', lead='Codex', galaxy=true;
const drafts=new Map();
const examples={
plan:{title:'A weekend worth making',prompt:'Help me plan a small volunteer day for our neighborhood. We have one Saturday and five people.',answer:'<h3>Start small. Make it a good Saturday.</h3><p>Pick one shared space, give everyone a clear role, and leave time to enjoy what you made together.</p><ul><li><strong>9:00 — Meet and make a plan.</strong> Walk the space and choose three achievable jobs.</li><li><strong>9:30 — Work in pairs.</strong> Keep one person free for supplies and questions.</li><li><strong>11:30 — Wrap up together.</strong> Take a photo, share lunch, and note what to try next time.</li></ul>',review:'One perspective suggested a full-day event. The other preferred a shorter session. This sample draft keeps the smaller scope so five people can finish without rushing.'},
website:{title:'A home for the book club',prompt:'What should go on a simple website for our neighborhood book club?',answer:'<h3>A warm welcome. One clear invitation.</h3><p>Make it easy for someone new to find the next gathering and feel comfortable joining.</p><ul><li><strong>Next gathering:</strong> the book, date, and location.</li><li><strong>What to expect:</strong> a relaxed discussion, with no pressure to finish every page.</li><li><strong>Join us:</strong> one simple way to contact the organizer.</li></ul><p>Keep past reading lists on their own page, so the invitation has room to breathe.</p>',review:'This prewritten review removes an unnecessary member dashboard and keeps the first version focused on attending a gathering. No website files are generated by this demo.'}
};
function remember(){drafts.set(current,draft.value);}
function render(view){
remember(); current=view; draft.value=drafts.get(current)||'';
const team=view==='team', fresh=view==='new';
$('#tour-composer').hidden=team;
$('#tour-mode').textContent=team?'Team concept':fresh?'Local draft':'Sample conversation';
document.querySelectorAll('[data-view]').forEach(b=>{if(b.dataset.view===(team?'team':fresh?'new':'conversation'))b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});
document.querySelectorAll('[data-example]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.example===view)));
if(team){
$('#tour-title').textContent='Your AI team';
content.innerHTML='<p class="tour-label" style="margin-left:0">ONE TEAM. DIFFERENT STRENGTHS.</p><h3>You choose the lead.</h3><p>The planned experience lets your lead choose independent perspectives, divided tasks, or a combination. You stay in control.</p><div class="tour-team"><div class="tour-member"><span class="tour-avatar">C</span><div><strong>Codex</strong><small>Example team member</small></div><span class="tour-pill" data-role="Codex"></span></div><div class="tour-member"><span class="tour-avatar">C</span><div><strong>Claude</strong><small>Example team member</small></div><span class="tour-pill" data-role="Claude"></span></div></div><div class="tour-team-controls" role="group" aria-label="Preview lead selection"><button data-lead="Codex">Codex leads</button><button data-lead="Claude">Claude leads</button></div><p class="tour-disclosure">Design concept only. Neither provider is connected. This selection changes the preview, not a real AI team.</p>';
content.querySelectorAll('[data-lead]').forEach(b=>b.addEventListener('click',()=>{lead=b.dataset.lead;renderLead();$('#tour-status').textContent=lead+' is the example lead. No provider settings were changed.';}));renderLead();
}else if(fresh){$('#tour-title').textContent='New conversation';content.innerHTML='<div class="tour-empty"><img src="/rivune/assets/rivune-icon-128.png" alt=""><h3>What are we working on?</h3><p>Try writing a draft below, or open a sample conversation.<br>This preview does not generate AI answers.</p></div>';
}else{const e=examples[view];$('#tour-title').textContent=e.title;content.innerHTML='<div class="tour-user"></div><div class="tour-answer-label"><img src="/rivune/assets/rivune-icon-128.png" alt="">Rivune · Prewritten example</div>'+e.answer+'<details><summary>See the thinking behind this example</summary><p></p></details>';content.querySelector('.tour-user').textContent=e.prompt;content.querySelector('details p').textContent=e.review;}
$('#tour-status').textContent=team?'Explore the planned team controls.':fresh?'Draft kept while you explore. Leaving or reloading this page clears it.':'Prewritten example. No AI request was sent.';
}
function renderLead(){content.querySelectorAll('[data-role]').forEach(el=>el.textContent=el.dataset.role===lead?'Lead':'Member');content.querySelectorAll('[data-lead]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.lead===lead)));}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>render(b.dataset.view==='conversation'?'plan':b.dataset.view)));
document.querySelectorAll('[data-example]').forEach(b=>b.addEventListener('click',()=>render(b.dataset.example)));
draft.addEventListener('input',remember);
$('#tour-composer').addEventListener('submit',e=>{e.preventDefault();remember();$('#tour-status').textContent=draft.value.trim()?'Draft kept in this preview. Leaving or reloading clears it; nothing was sent to an AI.':'Write a draft first. This preview does not send AI requests.';});
const dialog=$('#tour-dialog');$('#tour-settings').addEventListener('click',()=>dialog.showModal());$('#tour-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>$('#tour-settings').focus());
$('#tour-galaxy').addEventListener('click',()=>{galaxy=!galaxy;$('.tour').classList.toggle('no-galaxy',!galaxy);$('#tour-galaxy').setAttribute('aria-checked',String(galaxy));$('#tour-galaxy').textContent=galaxy?'On':'Off';});
render('plan');
})();
