'use strict';
const $=s=>document.querySelector(s), copy=x=>JSON.parse(JSON.stringify(x));
const capabilities={codex:{label:'Codex CLI',models:{atlas:{label:'Sample Atlas',efforts:['low','medium','high']},swift:{label:'Sample Swift',efforts:['low','medium']}}},claude:{label:'Claude CLI',models:{lyra:{label:'Sample Lyra',efforts:['medium','high']}}}};
let serial=3;
let saved={members:[{id:'member-01',name:'Member 1',route:'codex',model:'atlas',effort:'high'},{id:'member-02',name:'Member 2',route:'codex',model:'swift',effort:'medium'},{id:'member-03',name:'Member 3',route:'claude',model:'lyra',effort:'high'}],orchestrator:'member-01',fallback:'stop',order:['member-02','member-03']};
let draft,run=null,scenario='ready';
const modelLabel=m=>m.model?capabilities[m.route].models[m.model].label:'Account default (unresolved)';
const available=m=>!(scenario==='claude-off'&&m.route==='claude')&&!(scenario==='model-off'&&m.route==='codex'&&m.model==='atlas');
const label=m=>`${m.name} · ${capabilities[m.route].label} · ${modelLabel(m)}`;
function option(value,text,selected,disabled=false){return `<option value="${value}" ${selected?'selected':''} ${disabled?'disabled':''}>${text}</option>`}
function announce(text){$('#notice').textContent=text}
function normalize(){draft.order=draft.order.filter(id=>id!==draft.orchestrator&&draft.members.some(m=>m.id===id));draft.members.forEach(m=>{if(m.id!==draft.orchestrator&&!draft.order.includes(m.id))draft.order.push(m.id)})}
function renderEditor(){normalize();$('#members').innerHTML=draft.members.map(m=>`<article class="member" data-id="${m.id}"><div class="member-head"><div><strong>${m.name}</strong><span class="member-id">${m.id===draft.orchestrator?'Orchestrator + independent member':'Independent member'}</span></div><button type="button" data-action="remove" ${draft.members.length<=2?'disabled':''} aria-label="Remove ${m.name}">Remove</button></div><div class="member-controls"><label>Provider<select data-field="route" aria-label="Provider for ${m.name}">${Object.entries(capabilities).map(([k,v])=>option(k,v.label,k===m.route)).join('')}${option('gemini','Gemini CLI — no adapter',false,true)}</select></label><label>Model · sample catalog<select data-field="model" aria-label="Model for ${m.name}">${option('','Account default · unresolved',!m.model)}${Object.entries(capabilities[m.route].models).map(([k,v])=>option(k,v.label+(scenario==='model-off'&&k==='atlas'?' — unavailable':''),k===m.model,scenario==='model-off'&&k==='atlas')).join('')}</select></label><label>Reasoning<select data-field="effort" aria-label="Reasoning for ${m.name}">${option('','Account default · unresolved',!m.effort)}${['low','medium','high','max'].map(v=>option(v,v+(!m.model||!capabilities[m.route].models[m.model].efforts.includes(v)?' — unsupported':''),v===m.effort,!m.model||!capabilities[m.route].models[m.model].efforts.includes(v))).join('')}</select></label></div><p class="readiness ${available(m)?'':'bad'}">${available(m)?'Sample access available · never execution-verified':scenario==='claude-off'?'Unavailable · sample sign-in required':'Unavailable · selected model missing from sample catalog'}</p><details class="member-details"><summary>Member details</summary><small>Demo member ID: ${m.id}</small></details></article>`).join('');
$('#orchestrator').innerHTML=draft.members.map(m=>option(m.id,label(m)+(available(m)?'':' — unavailable'),m.id===draft.orchestrator,!available(m))).join('');$('#fallback').value=draft.fallback;$('#add').disabled=draft.members.length>=6;
$('#order').innerHTML=draft.fallback==='ordered'?`<p class="note">Only these saved members may take over. Unavailable or failed members are skipped; if none qualifies, stop and retain work.</p>`+draft.order.map((id,i)=>`<div class="order-row"><span>${i+1}. ${draft.members.find(m=>m.id===id).name}</span><div class="order-buttons"><button type="button" data-move="${i}" data-delta="-1" aria-label="Move ${draft.members.find(m=>m.id===id).name} earlier" ${i===0?'disabled':''}>↑</button><button type="button" data-move="${i}" data-delta="1" aria-label="Move ${draft.members.find(m=>m.id===id).name} later" ${i===draft.order.length-1?'disabled':''}>↓</button></div></div>`).join(''):'';
$('#edit-note').textContent=run?'A task already has a frozen snapshot. Saving here changes future tasks only.':'Saving updates the team for future tasks only.';$('#validation').textContent=draft.members.some(m=>!available(m))?'This team contains unavailable selections. You can save it, but starting a task is blocked until all members are available.':'';
}
function renderSummary(){$('#team-open').innerHTML=`Team · ${saved.members.length} <span aria-hidden="true">↗</span>`;$('#summary').textContent=`Orchestrator: ${saved.members.find(m=>m.id===saved.orchestrator).name} · ${modelLabel(saved.members.find(m=>m.id===saved.orchestrator))}`;$('#start').disabled=!!run?.active||saved.members.some(m=>!available(m));$('#start').title=saved.members.some(m=>!available(m))?'Open Team to resolve unavailable sample selections':''}
function closeEditor(){ $('#team-dialog').close();$('#team-open').focus() }
$('#team-open').onclick=()=>{draft=copy(saved);renderEditor();$('#team-dialog').showModal();$('.dialog-body').scrollTop=0;$('#close').focus()};$('#close').onclick=$('#cancel').onclick=closeEditor;$('#team-dialog').addEventListener('cancel',()=>setTimeout(()=>$('#team-open').focus(),0));
$('#members').onchange=e=>{const f=e.target.dataset.field;if(!f)return;const id=e.target.closest('[data-id]').dataset.id,m=draft.members.find(m=>m.id===id);m[f]=e.target.value;if(f==='route'){m.model='';m.effort=''}if(f==='model')m.effort='';renderEditor();$(`[data-id="${id}"] [data-field="${f}"]`).focus()};
$('#members').onclick=e=>{if(e.target.dataset.action!=='remove')return;const id=e.target.closest('[data-id]').dataset.id;draft.members=draft.members.filter(m=>m.id!==id);if(draft.orchestrator===id)draft.orchestrator=draft.members[0].id;renderEditor();$('#add').focus()};
$('#add').onclick=()=>{if(draft.members.length>=6)return;serial++;draft.members.push({id:`member-${String(serial).padStart(2,'0')}`,name:`Member ${serial}`,route:'codex',model:'',effort:''});renderEditor();$(`[data-id="member-${String(serial).padStart(2,'0')}"] select`).focus()};
$('#orchestrator').onchange=e=>{draft.orchestrator=e.target.value;renderEditor();$('#orchestrator').focus()};$('#fallback').onchange=e=>{draft.fallback=e.target.value;renderEditor();$('#fallback').focus()};$('#order').onclick=e=>{if(!e.target.hasAttribute('data-move'))return;const i=Number(e.target.dataset.move),j=i+Number(e.target.dataset.delta);[draft.order[i],draft.order[j]]=[draft.order[j],draft.order[i]];const delta=e.target.dataset.delta;renderEditor();const next=$(`[data-move="${j}"][data-delta="${delta}"]`);(next&&!next.disabled?next:$('#fallback')).focus()};
$('#scenario').onchange=e=>{scenario=e.target.value;renderEditor();renderSummary()};$('#team-form').onsubmit=e=>{e.preventDefault();saved=copy(draft);renderSummary();closeEditor();announce('Team saved in demo memory. '+(run?'The existing task snapshot is unchanged.':'Ready for your next simulated task.'))};
function renderRun(){$('#run').hidden=false;$('#run-state').textContent=run.active?'Running · simulation':'Stopped · simulation';$('#run-prompt').textContent=run.prompt;$('#frozen').innerHTML=run.team.members.map(m=>`<div class="frozen-row"><span>${m.name}${m.id===run.team.orchestrator?' · Orchestrator':''}<details class="member-details"><summary>Member details</summary><small>Demo member ID: ${m.id}</small></details></span><span>${capabilities[m.route].label} · ${modelLabel(m)}<br>${m.effort||'Account default (unresolved)'}</span></div>`).join('')+`<p class="snapshot-policy">Frozen workflow: Council · Fallback: ${run.team.fallback==='stop'?'Stop and retain work':run.team.order.map(id=>run.team.members.find(m=>m.id===id).name).join(' → ')}<br>Up to 2 calls at once, and 1 per provider connection</p>`;$('#fail').disabled=$('#stop').disabled=!run.active;renderSummary()}
$('#start').onclick=()=>{if(run?.active||saved.members.some(m=>!available(m)))return;if(!$('#prompt').value.trim()){$('#prompt').focus();announce('Enter a prompt before simulating a task.');return}run={team:copy(saved),prompt:$('#prompt').value,active:true,appointed:saved.orchestrator,failed:[]};$('#run-event').textContent='Simulation paused at independent drafting. No answers or provider activity are fabricated.';renderRun();$('#run').scrollIntoView({block:'nearest'});$('#fail').focus();announce('A new task snapshot is frozen. You can edit the saved team while this simulation remains running.')};
$('#stop').onclick=()=>{run.active=false;$('#run-event').textContent='Stopped. Frozen configuration retained; no provider work was performed.';renderRun();$('#start').focus()};
$('#fail').onclick=()=>{run.failed.push(run.appointed);const next=run.team.fallback==='ordered'?run.team.order.find(id=>!run.failed.includes(id)&&available(run.team.members.find(m=>m.id===id))):null;if(next){run.appointed=next;$('#run-event').textContent=`Simulated fallback appointment: ${run.team.members.find(m=>m.id===next).name}. Uses the frozen order, assuming a successful independent draft. No model call was made.`}else{run.active=false;$('#run-event').textContent='Simulation stopped under the frozen fallback policy. Completed work would be retained; no new member or model is added.'}renderRun();if(!run.active)$('#start').focus()};
renderSummary();

// Keep keyboard traversal inside the modal, including browser-chrome boundaries.
$('#team-dialog').addEventListener('keydown',e=>{if(e.key!=='Tab')return;const items=[...$('#team-dialog').querySelectorAll('button:not(:disabled),select:not(:disabled),summary,[tabindex="0"]')].filter(el=>el.getClientRects().length);const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}});
