const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),crypto=require('crypto'),ts=require('../../../prototypes/ai-native-workspace/node_modules/typescript');const base=process.cwd()+'/prototypes/ai-native-workspace/src/',out=__dirname;
for(const line of fs.readFileSync(out+'/../source-hashes.txt','utf8').trim().split('\n')){const[h,p]=line.split(/  /);const b=fs.readFileSync(p);assert.equal(crypto.createHash('sha256').update(b).digest('hex'),h);fs.writeFileSync(out+'/'+p.split('/').at(-1),b)}
const transpile=s=>ts.transpileModule(s,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022}}).outputText;
const values=new Map(),storage={getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v),key:i=>[...values.keys()][i],get length(){return values.size}};
let slots=[],i=0,effects=[];const react={useState:v=>{const n=i++;if(!(n in slots))slots[n]=typeof v==='function'?v():v;return[slots[n],v=>slots[n]=typeof v==='function'?v(slots[n]):v]},useRef:v=>{const n=i++;return slots[n]??(slots[n]={current:v})},useCallback:f=>f,useEffect:f=>effects.push(f)};
const cache={};function load(path){if(cache[path])return cache[path];const exports={};cache[path]=exports;vm.runInNewContext(transpile(fs.readFileSync(path,'utf8')),{exports,require:n=>n==='react'?react:load(require('path').resolve(require('path').dirname(path),n)+'.ts'),window:{sessionStorage:storage,clearTimeout:()=>{}},queueMicrotask});return exports}
const draft=load(base+'hooks/draftStore.ts'),hook=load(base+'hooks/useWorkspaceDemo.ts');let store=draft.createDraftStore(()=>storage);function render(){i=0;effects=[];const state=hook.useWorkspaceDemo();effects.forEach(f=>f());return state}
let w=render();const first=w.activeConversationId;store.setDraft(first,'Original exact 🪐');w.newConversation();w=render();const second=w.activeConversationId;assert.notEqual(second,first);assert.equal(store.getDraft(second),'');store.setDraft(second,'Second');w.selectConversation(first);w=render();assert.equal(store.getDraft(w.activeConversationId),'Original exact 🪐');slots=[];w=render();store=draft.createDraftStore(()=>storage);assert.equal(w.activeConversationId,first);assert.equal(store.getDraft(first),'Original exact 🪐');assert.equal(store.getDraft(second),'Second');console.log('PASS actual preview hook/store new-chat switch and fresh-instance reload using private Map storage');
// Execute the actual BrowserWorkspace with injected presentation data and hooks.
slots=[];let pending;let current={activeConversationId:'one',conversations:[{id:'one',title:'One'}],messages:[{id:'a',role:'assistant',content:'sample',artifactId:'a'},{id:'b',role:'assistant',content:'sample',artifactId:'b'}],artifacts:[{id:'a',title:'A',content:'TEXT A'},{id:'b',title:'B',content:'TEXT B'}],agents:[],selectConversation:()=>{},newConversation:()=>{}};
const ex={};react.useSyncExternalStore=(_,get)=>get();vm.runInNewContext(transpile(fs.readFileSync(out+'/BrowserWorkspace.tsx','utf8')),{exports:ex,require:n=>n==='react'?react:n==='react/jsx-runtime'?{jsx:(type,props)=>({type,props}),jsxs:(type,props)=>({type,props})}:n.includes('useWorkspaceDemo')?{useWorkspaceDemo:()=>current}:n.includes('draftStore')?{browserDraftStore:store}:n.includes('button')?{Button:'button'}:{},navigator:{clipboard:{writeText:()=>new Promise(r=>pending=r)}},requestAnimationFrame:()=>{}});
function nodes(x,a=[]){if(Array.isArray(x))x.forEach(y=>nodes(y,a));else if(x&&typeof x==='object'){a.push(x);nodes(x.props?.children,a)}return a}function ui(){i=0;effects=[];return ex.BrowserWorkspace()}let tree=ui();let list=nodes(tree);list.find(x=>x.props?.className==='bw-results-trigger').props.onClick();tree=ui();list=nodes(tree);const resultDialog=list.find(x=>x.props?.className==='bw-dialog bw-results');nodes(resultDialog).find(x=>x.props?.className==='bw-result-card').props.onClick();tree=ui();list=nodes(tree);const copying=list.find(x=>x.props?.children==='Copy sample text').props.onClick();list.find(x=>x.props?.className==='bw-back').props.onClick();tree=ui();const cards=nodes(nodes(tree).find(x=>x.props?.className==='bw-dialog bw-results')).filter(x=>x.props?.className==='bw-result-card');cards[1].props.onClick();pending();copying.then(()=>{const now=nodes(ui());assert(now.some(x=>x.type==='pre'&&x.props.children==='TEXT B'));assert(now.some(x=>x.props?.role==='status'&&x.props.children==='Copied sample text'));console.log('REPRODUCED stale copy of A announces success on B; clipboard is synthetic, no OS write');});
