import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createModelDiscoveryAdapter, parseModelDiscovery } from '../src/host/modelDiscovery.ts';
const request={requestID:'synthetic-request',providerID:'synthetic-codex-route'};
function report(){return {...request,schemaVersion:1,source:'codexAppServerModelList',scope:'isolatedUnauthenticated',state:'unauthenticated',authentication:'notAuthenticated',selectionEnabled:false,models:[{id:'synthetic-picker-id',model:'synthetic-wire-model',label:'Synthetic model',reasoningEfforts:['future-effort'],defaultReasoningEffort:'future-effort',isDefault:true}],errorCode:null};}
test('discovered IDs and advertised effort strings remain separate from admission',()=>{const r=parseModelDiscovery(report(),request);assert.equal(r.models[0].model,'synthetic-wire-model');assert.equal(r.models[0].reasoningEfforts[0],'future-effort');assert.equal(r.selectionEnabled,false);});
test('foreign identities, schemas, entitlement claims and malformed models fail closed',()=>{for(const mutate of [r=>{r.requestID='foreign'},r=>{r.providerID='other'},r=>{r.schemaVersion=2},r=>{r.selectionEnabled=true},r=>{r.authentication='authenticated'},r=>{r.models[0].defaultReasoningEffort='missing'},r=>{r.models.push({...r.models[0]})},r=>{r.privateAccount='hidden'}]){const r=report();mutate(r);assert.throws(()=>parseModelDiscovery(r,request));}});
test('missing optional discovery transport does not invoke getters or create a server',()=>{let calls=0;assert.equal(createModelDiscoveryAdapter({get discoverProviderModels(){calls++;throw Error('no');}}),null);assert.equal(calls,0);assert.equal(createModelDiscoveryAdapter({discoverProviderModels(){calls++;}}),null);});
test('adapter binds exact request and returns sanitized errors for mismatched replies',async()=>{const calls=[];const a=createModelDiscoveryAdapter({discoverProviderModels:async r=>{calls.push(r);return report()},cancelModelDiscovery:async()=>true});assert.equal((await a.discover(request)).state,'unauthenticated');assert.deepEqual(calls,[request]);const bad=createModelDiscoveryAdapter({discoverProviderModels:async()=>({...report(),requestID:'other'}),cancelModelDiscovery:async()=>true});assert.equal((await bad.discover(request)).errorCode,'DISCOVERY_PROTOCOL_ERROR');});
test('abort waits for native cleanup outcome and does not claim termination on acknowledgement',async()=>{
 let release;const calls=[];const a=createModelDiscoveryAdapter({discoverProviderModels:()=>new Promise(r=>{release=r}),cancelModelDiscovery:async id=>{calls.push(id);return false}});
 const c=new AbortController();let settled=false;const pending=a.discover(request,c.signal).then(r=>{settled=true;return r});await Promise.resolve();c.abort();await Promise.resolve();await Promise.resolve();assert.equal(settled,false);assert.deepEqual(calls,[request.requestID]);
 release({...report(),state:'error',authentication:'unknown',models:[],errorCode:'DISCOVERY_CLEANUP_PENDING'});assert.equal((await pending).errorCode,'DISCOVERY_CLEANUP_PENDING');
});
test('late success after abort cannot claim completed cancellation or expose models',async()=>{
 let release;const a=createModelDiscoveryAdapter({discoverProviderModels:()=>new Promise(r=>{release=r}),cancelModelDiscovery:async()=>true});const c=new AbortController();const pending=a.discover(request,c.signal);await Promise.resolve();c.abort();release(report());const r=await pending;assert.equal(r.errorCode,'DISCOVERY_CANCELLATION_UNCONFIRMED');assert.deepEqual(r.models,[]);
});
test('pre-aborted request never invokes discovery',async()=>{let calls=0;const a=createModelDiscoveryAdapter({discoverProviderModels:()=>{calls++;return report()},cancelModelDiscovery:async()=>true});const c=new AbortController();c.abort();assert.equal((await a.discover(request,c.signal)).state,'cancelled');assert.equal(calls,0);});

test('cleanup failure remains an error with no advertised models or selection',()=>{const r={...report(),state:'error',authentication:'unknown',models:[],errorCode:'DISCOVERY_CLEANUP_FAILED'};assert.equal(parseModelDiscovery(r,request).errorCode,'DISCOVERY_CLEANUP_FAILED');assert.throws(()=>parseModelDiscovery({...r,models:report().models},request));assert.throws(()=>parseModelDiscovery({...r,selectionEnabled:true},request));});
test('frontend deadline reports unconfirmed termination rather than completed cancellation',async t=>{t.mock.timers.enable({apis:['setTimeout']});const calls=[];const a=createModelDiscoveryAdapter({discoverProviderModels:()=>new Promise(()=>{}),cancelModelDiscovery:async id=>{calls.push(id);return true}});const pending=a.discover(request);await Promise.resolve();t.mock.timers.tick(10000);const r=await pending;assert.equal(r.state,'timeout');assert.equal(r.errorCode,'DISCOVERY_TERMINATION_UNCONFIRMED');assert.deepEqual(calls,[request.requestID]);assert.deepEqual(r.models,[]);});
