const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),crypto=require('crypto'),ts=require('../../../prototypes/ai-native-workspace/node_modules/typescript');
const dir=__dirname,root=process.cwd(),manifest=JSON.parse(fs.readFileSync(dir+'/../source-hashes.json'));for(const [p,h]of Object.entries(manifest)){const b=fs.readFileSync(root+'/'+p);assert.equal(crypto.createHash('sha256').update(b).digest('hex'),h.afterSHA256);if(h.beforeSHA256)assert.equal(crypto.createHash('sha256').update(fs.readFileSync(dir+'/../before/'+p)).digest('hex'),h.beforeSHA256)}
const source=fs.readFileSync(root+'/prototypes/ai-native-workspace/src/StartupFallback.tsx','utf8');fs.writeFileSync(dir+'/StartupFallback.tsx',source);
const code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022}}).outputText;
const gate=()=>{let resolve,reject;return{promise:new Promise((a,b)=>{resolve=a;reject=b}),resolve:v=>resolve(v),reject:e=>reject(e)}};const flush=async()=>{for(let i=0;i<8;i++)await Promise.resolve()};
(async()=>{for(const oldOutcome of ['resolve','reject']){let state={},effect,updates=0;const exports={};vm.runInNewContext(code,{exports,require:n=>n==='react'?{Component:class{},useState:()=>[state,v=>{state=v;updates++}],useEffect:f=>effect=f}:n==='react/jsx-runtime'?{jsx:(type,props)=>({type,props}),jsxs:(type,props)=>({type,props})}:{}});
 const old=gate(),fresh=gate();let calls=0;const load=()=>++calls===1?old.promise:fresh.promise;exports.StartupLoader({load});const cleanupOld=effect();cleanupOld();const cleanupFresh=effect();await flush();const Fresh=()=>null;fresh.resolve({default:Fresh});await flush();assert.equal(state.module.default,Fresh);const before=updates;if(oldOutcome==='resolve')old.resolve({default:()=>null});else old.reject(Error('old private failure'));await flush();assert.equal(updates,before);assert.equal(state.module.default,Fresh);cleanupFresh();console.log('PASS StrictMode abandoned '+oldOutcome+' cannot overwrite active module');
 const pending=gate();exports.StartupLoader({load:()=>pending.promise});const dispose=effect();await flush();dispose();const baseline=updates;pending.reject(Error('disposed'));await flush();assert.equal(updates,baseline);console.log('PASS disposed rejection ignored');
 const boundary=new exports.StartupBoundary();boundary.props={children:'healthy'};assert.equal(boundary.render(),'healthy');boundary.state=exports.StartupBoundary.getDerivedStateFromError();boundary.props={children:'replacement'};assert.equal(boundary.render().props.state,'failed');console.log('PASS boundary remains failed across child replacement');
}
const app=fs.readFileSync(root+'/prototypes/ai-native-workspace/src/App.tsx','utf8');const ast=ts.createSourceFile('App.tsx',app,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);const fn=ast.statements.find(s=>ts.isFunctionDeclaration(s)&&s.name?.text==='App').getText(ast);const compiled=ts.transpileModule(fn,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText;
for(const mode of ['demo','missing','null','primitive','accessor','object']){let getters=0;const window={};if(mode!=='demo')Object.defineProperty(window,'__TAURI_INTERNALS__',{get(){getters++;throw Error('marker getter')}});if(mode==='accessor')Object.defineProperty(window,'__RIVUNE_DESKTOP_HOST__',{get(){getters++;throw Error('bridge getter')}});else if(!['demo','missing'].includes(mode))window.__RIVUNE_DESKTOP_HOST__=mode==='null'?null:mode==='primitive'?1:{};const exports={};vm.runInNewContext(compiled,{exports,window,HostWorkspace:'host',DemoWorkspace:'demo',StartupFallback:'fallback',require:()=>({jsx:(type,props)=>({type,props})})});const result=exports.default();assert.equal(getters,0);assert.equal(result.type,mode==='demo'?'demo':mode==='object'?'host':'fallback');console.log('PASS actual App selector '+mode+' no getter invocation');}
})().catch(e=>{console.error(e);process.exitCode=1});
