(() => {
document.querySelectorAll('.mobile-menu a,.nav-more a').forEach((link) => { link.addEventListener('click', () => link.closest('details')?.removeAttribute('open')); });
document.addEventListener('keydown',event=>{if(event.key==='Escape')document.querySelectorAll('.mobile-menu[open],.nav-more[open]').forEach(details=>{details.removeAttribute('open');details.querySelector('summary')?.focus();});});
document.addEventListener('pointerdown',event=>{document.querySelectorAll('.mobile-menu[open],.nav-more[open]').forEach(details=>{if(!details.contains(event.target))details.removeAttribute('open');});});
const copyEmail=document.querySelector('[data-copy-email]');copyEmail?.addEventListener('click',async()=>{const status=document.querySelector('[data-copy-status]'),email=copyEmail.dataset.copyEmail;try{await navigator.clipboard.writeText(email);status.textContent='Email copied.';}catch(error){status.textContent='Copy failed. Select the email address above and copy it manually.';}});
const project={perspectives:['Two useful starting points','One perspective prioritizes a two-week pilot. Another starts with a smaller three-day test so the team can learn before committing.','The approaches disagree on scope. The review step will keep the low-risk test and a clear path to expand.'],review:['A smaller test, with a decision point','The review finds agreement on the goal and flags the timeline conflict. It combines a three-day trial with a written checkpoint before the full pilot.','The disagreement is visible instead of being averaged away.'],final:['A practical pilot plan','Run a three-day test with one owner, two participants, and a short success checklist. Review the evidence on day four, then decide whether to begin a two-week pilot.','Aarav can edit this draft before using it.']};
const stages={perspectives:'Perspectives',review:'Review',final:'Final draft'};let stage='perspectives';
const renderDemo=()=>{const panel=document.querySelector('[data-demo-label]')?.closest('.demo-panel');if(!panel)return;const data=project[stage];document.querySelector('[data-demo-label]').textContent=stages[stage];document.querySelector('[data-demo-title]').textContent=data[0];document.querySelector('[data-demo-body]').textContent=data[1];document.querySelector('[data-demo-note]').textContent=data[2];document.querySelectorAll('[data-demo-stage]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.demoStage===stage)));};
document.querySelectorAll('[data-demo-stage]').forEach(b=>b.addEventListener('click',()=>{stage=b.dataset.demoStage;renderDemo();}));
const platformPanel=document.querySelector('[data-platform-panel]'),macReady=platformPanel?.dataset.releaseReady==='true';const platforms={mac:['macOS',document.querySelector('[data-platform-title]')?.textContent,document.querySelector('[data-platform-body]')?.textContent],windows:['Windows','Windows download not yet available','The desktop app is in development. The Windows download is not yet available.'],linux:['Linux','Linux download not yet available','The desktop app is in development. The Linux download is not yet available.']};
document.querySelectorAll('[data-platform]').forEach(b=>b.addEventListener('click',()=>{const p=b.dataset.platform,d=platforms[p],panel=document.querySelector('[data-platform-panel]');document.querySelectorAll('[data-platform]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.querySelectorAll('[data-mac-only]').forEach(x=>x.hidden=p!=='mac');document.querySelector('[data-platform-label]').textContent=d[0];document.querySelector('[data-platform-title]').textContent=d[1];document.querySelector('[data-platform-body]').textContent=d[2];panel.focus();}));
})();