import test from 'node:test';
import assert from 'node:assert/strict';
import {fixture,count,enableTeam} from './reviewerFixture.mjs';
import {composerConfigurationKey as key} from '../src/host/composerConfiguration.ts';
import {configuredTeam} from '../src/host/teamConfiguration.ts';
for(const recovered of [false,true])for(const drift of ['revision','catalog','route'])test(`supersession recovered=${recovered} rejects captured ${drift} drift then accepts without writes`,async t=>{
 const f=fixture();enableTeam(f);f.snapshot.attachments=[{attachmentID:'a',conversationID:'chat',displayName:'Synthetic',byteLength:1,sha256:'a'.repeat(64),sourceState:'valid'}];f.snapshot.conversations[0].richDraft.attachmentIDs=['a'];const c=f.controller();t.after(()=>c.dispose());await c.start();c.editDraft('chat','Local original');const s=c.getState(),team=configuredTeam(s.snapshot,s.catalog,['codex','claude'],'claude');const original=f.bridge.saveRichDraft;let receipt,request;
 f.bridge.saveRichDraft=async r=>{if(receipt){assert.deepEqual(r,request);f.calls.push(['save',structuredClone(r)]);return structuredClone(receipt);}request=structuredClone(r);receipt=await original(r);f.snapshot.conversations[0].draft='External message';Object.assign(f.snapshot.conversations[0].richDraft,{revision:4,team:null,selection:null});if(recovered)throw Error('lost');return receipt;};
 await assert.rejects(c.configureExecution('chat',{expectedKey:key(s.snapshot,s.catalog,'chat'),selection:team.members[1],team}));
 if(recovered){await c.refresh();const n=count(f,'save');await assert.rejects(c.acceptSupersedingConfiguration('chat',key(c.getState().snapshot,c.getState().catalog,'chat')));assert.equal(count(f,'save'),n);assert.equal(c.getState().configurationConfirmations.chat.acknowledged,false);await assert.rejects(c.retryDraftSave('chat'));assert.equal(count(f,'save'),2);}
 assert.equal(c.getState().configurationConfirmations.chat.acknowledged,true);const captured=key(c.getState().snapshot,c.getState().catalog,'chat');c.editDraft('chat','Newest local text');
 const read=f.bridge.getSnapshot,readCatalog=f.bridge.getModelCatalog;let release;const gate=new Promise(r=>release=r);f.bridge.getSnapshot=async()=>{await gate;return read();};f.bridge.getModelCatalog=async()=>{await gate;return readCatalog();};const pending=c.acceptSupersedingConfiguration('chat',captured);
 if(drift==='revision'){f.snapshot.conversations[0].richDraft.revision=5;f.snapshot.conversations[0].draft='Second external message';}if(drift==='catalog')f.catalog.revision='catalog-v2';if(drift==='route')f.snapshot.providers[0].executablePath='/fixture/changed';release();f.bridge.getSnapshot=read;f.bridge.getModelCatalog=readCatalog;
 await assert.rejects(pending,/changed again/);assert(c.getState().configurationConfirmations.chat);assert.equal(c.getState().drafts.chat,'Newest local text');const before=count(f,'save'),expectedRevision=f.snapshot.conversations[0].richDraft.revision,hostBefore=structuredClone(f.snapshot);
 await c.acceptSupersedingConfiguration('chat',key(c.getState().snapshot,c.getState().catalog,'chat'));assert.equal(c.getState().configurationConfirmations.chat,undefined);assert.equal(c.getState().drafts.chat,'Newest local text');assert.deepEqual(f.snapshot,hostBefore);assert.equal(count(f,'save'),before);assert.equal(count(f,'submit'),0);assert.equal(count(f,'journal.write'),0);
 f.bridge.saveRichDraft=original;await c.saveDraft('chat');const saved=f.calls.filter(x=>x[0]==='save').at(-1)[1];assert.equal(saved.expectedRevision,expectedRevision);assert.equal(saved.draft,'Newest local text');assert.deepEqual(saved.attachmentIDs,['a']);assert.equal(saved.team,null);assert.equal(saved.selection,null);assert.equal(count(f,'save'),before+1);assert.equal(count(f,'submit'),0);
});
