const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {chromium}=require('/Users/Aaravshah/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{
 const browser=await chromium.launch({executablePath:'/Users/Aaravshah/Library/Caches/ms-playwright/chromium_headless_shell-1223/chrome-headless-shell-mac-arm64/chrome-headless-shell',headless:true});
 const checks=[],errors=[],requests=[];const check=(name,value)=>{assert.ok(value,name);checks.push({name,pass:true})};
 try{
 const context=await browser.newContext({viewport:{width:1120,height:760},reducedMotion:'reduce'});
 await context.route('**/*',async route=>{
  const url=new URL(route.request().url());if(url.origin!=='https://rivune-transcript.test'){requests.push(url.href);return route.abort()}
  const name=url.pathname.slice(1)||'index.html',file=path.resolve(__dirname,'web',name);
  if(!file.startsWith(path.join(__dirname,'web')+path.sep)||!fs.existsSync(file))return route.abort();
  const types={'.mjs':'text/javascript','.js':'text/javascript','.css':'text/css','.html':'text/html','.json':'application/json','.png':'image/png','.svg':'image/svg+xml'};
  await route.fulfill({body:fs.readFileSync(file),contentType:types[path.extname(file)]||'text/plain'});
 });
 const page=await context.newPage();page.on('pageerror',e=>errors.push(String(e)));await page.goto('https://rivune-transcript.test/',{waitUntil:'networkidle'});
 check('actual Rust-serialized record maps to visible prompt and answer',await page.evaluate(()=>document.querySelector('.user-message').textContent==='fixture'&&document.querySelector('.markdown').textContent==='fixture answer'));
 const markdown='# A thoughtful workshop\n\nStart with **one good question**, then make room for *different perspectives*.\n\n1. Read a short story.\n2. Discuss what changed.\n\n> Leave space for a surprising answer.\n\n| Step | Time |\n| --- | --- |\n| Reading | 10 min |\n| Discussion | 15 min |\n\n```js\nconst title = "Reading together";\nconsole.log(title);\n```\n\n[Reference](https://example.com/reading)';
 await page.evaluate(text=>{
  const r=window.review,s=r.snapshot;s.runs[0].admitted.prompt='Create a clear reading workshop plan with a short example.';s.runs[0].answer=text;s.runs[0].admitted.provider.kind='claude';s.runs[0].admitted.provider.model='fixture-model';r.transcript.render(s,'welcome');document.querySelector('.response-scroll').scrollTop=0;
 },markdown);
 check('Markdown heading, emphasis, table, code and quote render',await page.evaluate(()=>!!document.querySelector('.markdown h2')&&!!document.querySelector('.markdown strong')&&!!document.querySelector('.markdown table')&&!!document.querySelector('.markdown blockquote')&&!!document.querySelector('.code-block')));
 await page.screenshot({path:path.join(__dirname,'evidence/desktop-history.png')});
 check('code remains readable at the desktop minimum font size',await page.locator('.code-block code').evaluate(e=>parseFloat(getComputedStyle(e).fontSize)>=13));
 await page.locator('.code-header button').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(__dirname,'evidence/desktop-code.png')});
 await page.locator('.code-header button').click();check('copy preserves code exactly',await page.evaluate(()=>window.review.copied[0]==='const title = "Reading together";\nconsole.log(title);'));
 await page.locator('.markdown [role=link]').click();check('external link uses injected opener',await page.evaluate(()=>window.review.opened[0]==='https://example.com/reading'));
 await page.locator('.code-header button').focus();
 check('unchanged polling preserves focused code button',await page.evaluate(()=>{const old=document.activeElement;window.review.transcript.render(structuredClone(window.review.snapshot),'welcome');return document.activeElement===old}));
 check('same-answer status transition preserves code DOM',await page.evaluate(()=>{const old=document.activeElement;window.review.snapshot.runs[0].status='running';window.review.transcript.render(window.review.snapshot,'welcome');return document.activeElement===old&&document.querySelector('.message-state').textContent.includes('partial')}));
 check('partial append preserves an earlier focused code control',await page.evaluate(()=>{const r=window.review,old=document.activeElement;r.snapshot.runs[0].answer+='\n\nA later streamed paragraph.';r.transcript.render(r.snapshot,'welcome');return document.activeElement===old}));
 check('partial append preserves selected earlier text',await page.evaluate(()=>{const r=window.review,text=document.querySelector('.markdown h2').firstChild,selection=getSelection(),range=document.createRange();range.setStart(text,0);range.setEnd(text,5);selection.removeAllRanges();selection.addRange(range);const before=selection.toString();r.snapshot.runs[0].answer+='\n\nAnother later chunk.';r.transcript.render(r.snapshot,'welcome');const ok=selection.toString()===before;selection.removeAllRanges();return ok}));
 check('streaming extension preserves selection inside a growing paragraph',await page.evaluate(()=>{const r=window.review;r.snapshot.runs[0].answer='Beginning of the answer';r.transcript.render(r.snapshot,'welcome');const text=document.querySelector('.markdown p').firstChild,selection=getSelection(),range=document.createRange();range.setStart(text,0);range.setEnd(text,9);selection.removeAllRanges();selection.addRange(range);r.snapshot.runs[0].answer+=' continues here';r.transcript.render(r.snapshot,'welcome');const ok=selection.toString()==='Beginning';selection.removeAllRanges();return ok}));
 check('new reference links cannot steal focus from an existing target',await page.evaluate(()=>{const r=window.review;r.snapshot.runs[0].answer='[new][ref] [safe](https://safe.example)';r.transcript.render(r.snapshot,'welcome');document.querySelector('.external-link').focus();r.snapshot.runs[0].answer+='\n\n[ref]: https://new.example';r.transcript.render(r.snapshot,'welcome');return document.activeElement.title==='https://safe.example/'}));
 check('linked image has one activation and opens only the enclosing target',await page.evaluate(async()=>{const opened=[];const node=window.review.renderMarkdown('[![alt](https://example.com/image.png)](https://example.com/article)',{document,openExternal:async u=>opened.push(u)});document.body.append(node);node.querySelector('[role=link]').click();await new Promise(r=>setTimeout(r,0));const ok=node.querySelectorAll('button').length===1&&opened.length===1&&opened[0]==='https://example.com/article';node.remove();return ok}));
 check('completed empty response is not presented as success',await page.evaluate(()=>{const s=window.review.snapshot;s.runs[0].status='completed';s.runs[0].answer='';window.review.transcript.render(s,'welcome');return document.querySelector('.message-state').textContent==='Finished without an answer'&&document.querySelector('.message-error').textContent.includes('without returning')}));
 await page.evaluate(()=>{const s=window.review.snapshot;s.runs[0].answer='Partial response';s.runs[0].status='failed';s.runs[0].error='Fixture provider stopped early';window.review.transcript.render(s,'welcome')});
 check('failed partial response and error both remain visible',await page.evaluate(()=>document.querySelector('.markdown').textContent==='Partial response'&&document.querySelector('.message-error').textContent==='Fixture provider stopped early'&&document.querySelector('.message-state').textContent.includes('partial')));
 check('foreign conversation is excluded and original order retained despite timestamps',await page.evaluate(()=>{
  const s=window.review.snapshot,a=structuredClone(s.runs[0]),b=structuredClone(a);a.id='r2';a.admitted.requestID='r2';a.admitted.retryOf='r1';a.updatedAt='1900';a.status='cancelled';b.id='other';b.conversationID='other';s.runs.push(a,b);window.review.transcript.render(s,'welcome');return [...document.querySelectorAll('.transcript-turn')].map(n=>n.dataset.runId).join(',')==='r1,r2'&&!!document.querySelector('.retry-note:not([hidden])')
 }));
 check('malformed snapshot preserves previously rendered history',await page.evaluate(()=>{const r=window.review,old=document.querySelector('#transcript').textContent,bad=structuredClone(r.snapshot);bad.runs.push(bad.runs[0]);let caught=false;try{r.transcript.render(bad,'welcome')}catch{caught=true}return caught&&old===document.querySelector('#transcript').textContent}));
 const hostile='<img src="https://evil.test/beacon" onerror="window.pwned=1">\n\n<script>window.pwned=2</script>\n\n[bad](javascript:alert(1)) [bad2](data:text/html,hi) [credential](https://u:p@example.com/) ![remote](https://evil.test/image)\n\n`&lt;literal&gt;` &amp; <iframe src="https://evil.test/frame"></iframe>';
 await page.evaluate(text=>{const r=window.review;r.snapshot.runs[0].answer=text;r.snapshot.runs[0].status='completed';r.transcript.render(r.snapshot,'welcome')},hostile);
 check('untrusted HTML stays inert without images or embedded content',await page.evaluate(()=>!window.pwned&&!document.querySelector('#transcript img,#transcript script,#transcript iframe,#transcript object')));
 check('unsafe link schemes and credentials never become links',await page.evaluate(()=>[...document.querySelectorAll('#transcript a')].every(a=>['https:','http:'].includes(new URL(a.href).protocol)&&!new URL(a.href).username)));
 check('code spans preserve entities literally',await page.evaluate(()=>document.querySelector('.markdown code').textContent==='&lt;literal&gt;'));
 check('external actions expose no browser-navigable href',await page.evaluate(()=>!document.querySelector('#transcript [href]')));
 check('no remote resource requests',requests.length===0);
 check('credential configs and approved context not present in projection',await page.evaluate(()=>{const r=window.review;const raw=JSON.stringify(r.projectConversation(r.snapshot,'welcome'));return !raw.includes('executablePath')&&!raw.includes('approvedContext')}));
 check('copy failure is reported without mutating answer',await page.evaluate(async()=>{let message='';const node=window.review.renderMarkdown('```txt\nkeep this\n```',{document,copyText:async()=>{throw Error('fixture')},report:m=>message=m});document.body.append(node);node.querySelector('button').click();await new Promise(r=>setTimeout(r,0));const ok=message.includes('Could not copy')&&node.querySelector('code').textContent==='keep this';node.remove();return ok}));
 check('links without an opener stay noninteractive',await page.evaluate(()=>!window.review.renderMarkdown('[x](https://example.com/)',{document}).querySelector('a')));
 check('large answer remains complete selectable plain text',await page.evaluate(()=>{const text='x'.repeat(250001),node=window.review.renderMarkdown(text,{document});return node.querySelector('.plain-response').textContent===text}));
 // Restore rich output, add later history, and verify a user reading earlier text is not pulled down.
 await page.evaluate(text=>{const r=window.review,s=r.snapshot;s.runs=s.runs.filter(x=>x.conversationID==='welcome');s.runs[0].answer=text;s.runs[0].error=null;s.runs[0].status='completed';s.runs[1].answer='A second response';s.runs[1].status='completed';r.transcript.render(s,'welcome');document.querySelector('.response-scroll').scrollTop=30},markdown);
 check('incoming result does not pull reader away from earlier text',await page.evaluate(()=>{const r=window.review,sc=document.querySelector('.response-scroll'),before=sc.scrollTop;r.snapshot.runs[1].answer+='\nMore content';r.transcript.render(r.snapshot,'welcome');return sc.scrollTop===before}));
 check('switching conversations restores reading position',await page.evaluate(()=>{const r=window.review,s=r.snapshot,sc=document.querySelector('.response-scroll');s.conversations.push({id:'c2',title:'Second',draft:''});const before=sc.scrollTop;r.transcript.render(s,'c2');r.transcript.render(s,'welcome');return sc.scrollTop===before}));
 for(const [width,height] of [[760,560],[390,844],[320,568]]){await page.setViewportSize({width,height});check(`no page horizontal overflow ${width}`,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.evaluate(()=>document.querySelector('.response-scroll').scrollTop=0);await page.screenshot({path:path.join(__dirname,`evidence/history-${width}.png`)})}
 check('no script errors',errors.length===0);
 fs.writeFileSync(path.join(__dirname,'evidence/REVIEW.json'),JSON.stringify({scope:'Browser rendering of actual Rust DTO fixture plus explicitly synthetic mutations. No live AI or app execution.',checks,errors,unexpectedRequests:requests},null,2)+'\n');console.log(JSON.stringify({checks:checks.length,errors}));
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
