const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),ts=require('../../../prototypes/ai-native-workspace/node_modules/typescript');
const code=ts.transpileModule(fs.readFileSync(__dirname+'/ProviderSetup.tsx','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022}}).outputText;
const gate=()=>{let resolve;return{promise:new Promise(r=>resolve=r),finish:v=>resolve(v)}};const flush=async()=>{for(let i=0;i<10;i++)await Promise.resolve()};
function harness(bridge,confirmed){let slots=[],index=0,cleanups=[],effects=[],fn,props={bridge,disabled:false,onConfirmed:confirmed,onContinue:()=>{throw Error('Unexpected handoff')}},tree;
 const react={useRef:v=>{const i=index++;return slots[i]??(slots[i]={current:v})},useState:v=>{const i=index++;if(!(i in slots))slots[i]=v;return[slots[i],v=>slots[i]=v]},useMemo:f=>{const i=index++;return slots[i]??(slots[i]=f())},useLayoutEffect:f=>{const i=index++;if(!(i in slots)){slots[i]=true;effects.push(f)}},useEffect:f=>{const i=index++;if(!(i in slots)){slots[i]=true;effects.push(f)}}};
 const module={exports:{}};vm.runInNewContext(code,{exports:module.exports,require:n=>n==='react'?react:n==='react/jsx-runtime'?{jsx:(type,p)=>({type,props:p}),jsxs:(type,p)=>({type,props:p})}:n.endsWith('.css')?{}:n==='./configurationRecovery'?{createConfigurationRecoveryAdapter:b=>b.recovery??null}:n==='./providerConfiguration'?{createProviderConfigurationAdapter:()=>({configure:async()=>({state:'durable'})}),prepareProviderConfiguration:()=>({})}:n==='./contracts'?{parseHostSnapshot:x=>x}:null});
 const outer=module.exports.ProviderSetup(props);fn=outer.type;slots=[];
 const render=()=>{index=0;tree=fn(props);for(const f of effects.splice(0)){const c=f();if(c)cleanups.push(c)};return tree};
 const nodes=(x,a=[])=>{if(!x)return a;if(Array.isArray(x)){x.forEach(v=>nodes(v,a));return a}if(typeof x==='object'){a.push(x);nodes(x.props?.children,a)}return a};
 return{render,unmount:()=>cleanups.forEach(f=>f()),button:text=>{render();return nodes(tree).find(x=>x.type==='button'&&x.props.children===text)?.props},select:()=>{render();return nodes(tree).find(x=>x.type==='select').props}};
}
(async()=>{
 let calls=0;const discovery=gate(),b={discoverProviders:()=>discovery.promise,getSnapshot:async()=>{calls++;return{}}};const h=harness(b,async()=>{throw Error('stale confirm')});h.render();h.button('Find installed providers').onClick();h.unmount();discovery.finish([{id:'codex:discovered:x',kind:'codex',executablePath:'/x',installed:true}]);await flush();assert.equal(calls,0);console.log('PASS late discovery does not request snapshot after cleanup');
 let confirmed=0;const recovery=gate(),r=harness({discoverProviders:async()=>[],getSnapshot:async()=>({}),recovery:{read:async()=>({}),reconcile:()=>recovery.promise}},async()=>{confirmed++});r.render();await flush();r.button('Check saved configuration').onClick();r.unmount();recovery.finish('applied');await flush();assert.equal(confirmed,0);console.log('PASS late applied recovery does not call parent refresh');
 const refresh=gate();let entered=0;const p=harness({discoverProviders:async()=>[{id:'codex:discovered:x',kind:'codex',executablePath:'/x',installed:true}],getSnapshot:async()=>({})},()=>{entered++;return refresh.promise});p.render();p.button('Find installed providers').onClick();await flush();p.select().onChange({target:{value:'codex:discovered:x'}});p.button('Save as workspace default').onClick();await flush();assert.equal(entered,1);assert.equal(p.button('Continue to chat').disabled,true);p.unmount();refresh.finish();await flush();assert.equal(entered,1);console.log('PASS pending parent refresh blocks handoff and late completion does not replay callback');
})().catch(e=>{console.error(e);process.exitCode=1});
