import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {root,verifyBundle} from './shared-bundle.mjs';
export function validateRelease(config, required = false) {
  if (!['development','stable','beta'].includes(config.channel)) throw Error('Unknown release channel');
  for (const kind of ['tauri','sparkle']) {
    const value = config[kind];
    if (!value || typeof value !== 'object') throw Error(`Missing ${kind} configuration`);
    const configured = value.endpoint != null || value.publicKey != null;
    if (!configured && !required) continue;
    let url; try { url = new URL(value.endpoint); } catch { throw Error(`${kind} needs an HTTPS release feed`); }
    if (url.protocol !== 'https:' || url.username || url.password || url.hash || !url.hostname || /(^|\.)example\.(com|org|net)$/.test(url.hostname)) throw Error(`${kind} needs a real HTTPS release feed without embedded credentials`);
    if (typeof value.publicKey !== 'string' || !value.publicKey.trim()) throw Error(`${kind} needs an update signing public key`);
    const decoded = Buffer.from(value.publicKey,'base64');
    if (kind === 'sparkle' && decoded.length !== 32) throw Error('Sparkle public key must decode to 32 bytes');
    if (kind === 'tauri' && !decoded.toString().startsWith('untrusted comment:')) throw Error('Use the public key generated by the Tauri signer');
  }
  if (required && config.channel === 'development') throw Error('Choose beta or stable before preparing a release');
  return config;
}
export async function prepareHosts(required = false) {
  const manifest = await verifyBundle();
  if (!/^\d+\.\d+\.\d+$/.test(manifest.version)) throw Error('Use a numeric major.minor.patch version for both desktop hosts');
  const config = validateRelease(JSON.parse(await readFile(join(root,'release/config.json'),'utf8')),required);
  const enabled = !!config.tauri.endpoint;
  const tauri = {version:manifest.version,build:{beforeBuildCommand:''},bundle:{createUpdaterArtifacts:enabled},plugins: enabled ? {updater:{pubkey:config.tauri.publicKey,endpoints:[config.tauri.endpoint],windows:{installMode:'passive'}}} : {}};
  await mkdir(join(root,'release/generated'),{recursive:true});
  await writeFile(join(root,'release/generated/tauri.conf.json'),JSON.stringify(tauri,null,2)+'\n');
  await writeFile(join(root,'release/generated/host.json'),JSON.stringify({version:manifest.version,sourceDigest:manifest.sourceDigest,channel:config.channel,sparkle:config.sparkle},null,2)+'\n');
  return {manifest,config};
}
if (process.argv[1] && resolve(process.argv[1])===fileURLToPath(import.meta.url)) await prepareHosts(process.argv.includes('--release'));
