const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {chromium}=require('/Users/Aaravshah/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=__dirname,web=path.resolve(root,'../cross-platform-shell-20260907/candidate4-runtime-r2/web');
(async()=>{
 const browser=await chromium.launch({executablePath:'/Users/Aaravshah/Library/Caches/ms-playwright/chromium_headless_shell-1223/chrome-headless-shell-mac-arm64/chrome-headless-shell',headless:true});
 const results=[],errors=[];const check=(name,result)=>{assert.ok(result,name);results.push({name,pass:true})};
 async function setup(options={}){
  const ctx=await browser.newContext({viewport:{width:1120,height:760},reducedMotion:'reduce'});
  await ctx.route('https://rivune-integrated.test/**',async route=>{const name=new URL(route.request().url()).pathname.slice(1)||'index.html',file=path.resolve(web,name);if(!file.startsWith(web+path.sep)||!fs.existsSync(file))return route.abort();const types={'.mjs':'text/javascript','.js':'text/javascript','.css':'text/css','.html':'text/html','.png':'image/png','.svg':'image/svg+xml'};await route.fulfill({body:fs.readFileSync(file),contentType:types[path.extname(file)]||'text/plain'})});
  const page=await ctx.newPage();page.on('pageerror',e=>errors.push(String(e)));
  await page.addInitScript(options=>{
   window.__polls=[];window.setInterval=cb=>{window.__polls.push(cb);return 1};
   const provider={id:'fixture:local',kind:'fixture',executablePath:'/fixture-only',model:null,timeoutMs:1000};
   const state={schemaVersion:1,selectedProviderID:options.noProvider?null:provider.id,providers:[provider],conversations:[{id:'c1',title:'Reading workshop',draft:''},{id:'c2',title:'Website ideas',draft:''}],runs:[]};
   const ctl=window.testHost={state,calls:[],failSave:!!options.failSave,failSnapshot:false,blockSave:false,saves:[],blockSnapshot:false,snapshots:[],blockSubmit:false,submits:[],failCreate:false};
   window.__RIVUNE_DESKTOP_HOST__={
    getSnapshot:async()=>{if(ctl.failSnapshot)throw Error('Fixture disconnected');const value=structuredClone(state);if(ctl.snapshotDelay)await new Promise(resolve=>setTimeout(resolve,ctl.snapshotDelay));if(ctl.blockSnapshot)await new Promise((resolve,reject)=>ctl.snapshots.push({resolve,reject}));return value},
    openConversation:async id=>{ctl.calls.push(['open',id])},
    createConversation:async c=>{if(ctl.failCreate)throw Error('fixture create failed');state.conversations.push({...c,draft:''})},
    configureProvider:async p=>{if(p.executablePath==='/bad')throw Error('Fixture invalid provider');state.selectedProviderID=p.id;ctl.calls.push(['configure',p])},
    saveDraft:async(id,draft)=>{ctl.calls.push(['save-start',id,draft]);if(ctl.failSave)throw Error('permission denied fixture');if(ctl.blockSave)await new Promise(resolve=>ctl.saves.push(resolve));state.conversations.find(c=>c.id===id).draft=draft;ctl.calls.push(['save-done',id,draft])},
    submitRun:async r=>{ctl.calls.push(['submit',r]);state.runs.push({id:r.id,conversationID:r.conversationID,status:'running',updatedAt:'2026-09-07',admitted:{requestID:r.id,conversationID:r.conversationID,prompt:r.prompt,mode:r.mode,provider,approvedContext:{},retryOf:null},answer:null,error:null});if(ctl.blockSubmit)await new Promise(resolve=>ctl.submits.push(resolve));return {state:'accepted',requestID:r.id}},
    reconcileRun:async id=>({state:'accepted',requestID:id}),
    cancelRun:async id=>{state.runs.find(r=>r.id===id).status='cancelled';return {state:'accepted',requestID:id}},
    retryRun:async(a,b)=>({state:'accepted',requestID:b})
   };
  },options);
  await page.goto('https://rivune-integrated.test/',{waitUntil:'networkidle'});return {page,ctx};
 }
 const tick=async p=>{await p.evaluate(()=>window.__polls.forEach(f=>f()));await p.waitForTimeout(15)};
 try{
  {const {page:p,ctx}=await setup({failSave:true});await p.locator('#prompt').fill('Keep this unsaved work');await p.waitForTimeout(220);await p.evaluate(()=>testHost.failSnapshot=true);await tick(p);await p.evaluate(()=>testHost.failSnapshot=false);await tick(p);check('failed save plus reconnect preserves unsaved text',await p.locator('#prompt').inputValue()==='Keep this unsaved work');await p.locator('#conversations button').nth(1).click();await p.locator('#prompt').fill('Separate B draft');await p.locator('#conversations button').first().click();check('failed save plus navigation retains each local draft',await p.locator('#prompt').inputValue()==='Keep this unsaved work');check('save warning remains pinned through polling',(await p.locator('#connection-status').textContent()).includes('couldn’t save'));await ctx.close()}
  {const {page:p,ctx}=await setup();await p.locator('#prompt').fill('Send only once');await p.locator('#submit').click();await p.waitForTimeout(230);check('accepted send cancels stale draft debounce',await p.evaluate(()=>testHost.state.conversations[0].draft==='')&&await p.locator('#prompt').inputValue()==='');await p.evaluate(()=>{testHost.state.runs[0].status='completed';testHost.state.runs[0].answer='# A good first session\n\nTry **one short story** and compare perspectives.\n\n```js\nconst idea = "Read together";\n```'});await tick(p);check('asynchronous completion renders full prompt and formatted answer',await p.locator('.user-message').textContent()==='Send only once'&&await p.locator('.markdown h2').textContent()==='A good first session');check('no unsupported copy or external-opener controls',await p.locator('.code-header button,.markdown [role=link]').count()===0);await p.locator('#conversations button').first().focus();await tick(p);check('poll preserves sidebar focus',await p.evaluate(()=>document.activeElement.matches('#conversations button')));await p.screenshot({path:path.join(root,'integrated-desktop.png')});await ctx.close()}
  {const {page:p,ctx}=await setup();await p.locator('#prompt').fill('Keep latest stored draft');await p.waitForTimeout(210);await p.locator('#conversations button').nth(1).click();await p.locator('#conversations button').first().click();check('navigation reads latest saved draft',await p.locator('#prompt').inputValue()==='Keep latest stored draft');await ctx.close()}
  {const {page:p,ctx}=await setup();await p.evaluate(()=>testHost.blockSave=true);await p.locator('#prompt').fill('One request during slow save');await p.evaluate(()=>{const form=document.querySelector('#prompt-form');form.dispatchEvent(new Event('submit',{cancelable:true}));form.dispatchEvent(new Event('submit',{cancelable:true}))});await p.waitForTimeout(15);check('slow pre-submit save admits one handler',await p.evaluate(()=>testHost.saves.length===1));await p.evaluate(()=>{testHost.blockSave=false;testHost.saves.shift()()});await p.waitForTimeout(25);check('slow save double-submit reaches host once',await p.evaluate(()=>testHost.calls.filter(c=>c[0]==='submit').length===1));await ctx.close()}
  {const {page:p,ctx}=await setup({failSave:true});await p.locator('#prompt').fill('Preserve on save rejection');await p.locator('#submit').click();await p.waitForTimeout(20);check('submit save rejection preserves draft without dispatch',await p.locator('#prompt').inputValue()==='Preserve on save rejection'&&await p.evaluate(()=>!testHost.calls.some(c=>c[0]==='submit')));await ctx.close()}
  {const {page:p,ctx}=await setup();await p.locator('#prompt').fill('A draft');await p.evaluate(()=>testHost.blockSnapshot=true);await p.locator('#conversations button').nth(1).click();await p.waitForTimeout(15);await tick(p);check('polling is suppressed during navigation',await p.evaluate(()=>testHost.snapshots.length===1));await p.locator('#prompt').fill('A edited during navigation');await p.evaluate(()=>{testHost.blockSnapshot=false;testHost.snapshots.shift().resolve()});await p.waitForTimeout(25);check('navigation atomically switches ID and displayed draft',await p.locator('#prompt').inputValue()==='');await p.locator('#conversations button').first().click();check('typing during navigation stays with source conversation',await p.locator('#prompt').inputValue()==='A edited during navigation');check('destination draft is not contaminated',await p.evaluate(()=>testHost.state.conversations[1].draft===''));await ctx.close()}
  {const {page:p,ctx}=await setup();await p.evaluate(()=>testHost.blockSnapshot=true);await tick(p);await p.evaluate(()=>testHost.blockSnapshot=false);await p.locator('#conversations button').nth(1).click();await p.locator('#prompt').fill('B remains selected');await p.evaluate(()=>testHost.snapshots.shift().reject(Error('Old failed poll')));await p.waitForTimeout(25);check('old failed poll cannot undo later navigation',await p.locator('#prompt').inputValue()==='B remains selected'&&await p.locator('#conversations button').nth(1).getAttribute('aria-pressed')==='true');await ctx.close()}
  {const {page:p,ctx}=await setup();await p.evaluate(()=>testHost.blockSubmit=true);await p.locator('#prompt').fill('Submitted A');await p.locator('#submit').click();await p.waitForTimeout(15);await p.locator('#conversations button').nth(1).click();await p.locator('#prompt').fill('Unsaved B');await p.evaluate(()=>testHost.submits.shift()());await p.waitForTimeout(25);check('late A acknowledgment leaves B draft intact',await p.locator('#prompt').inputValue()==='Unsaved B');await p.locator('#conversations button').first().click();check('late acknowledgment clears unchanged submitted A draft',await p.locator('#prompt').inputValue()==='');await ctx.close()}
  {const {page:p,ctx}=await setup();await p.evaluate(()=>testHost.blockSubmit=true);await p.locator('#prompt').fill('Old request');await p.locator('#submit').click();await p.waitForTimeout(15);await p.locator('#prompt').fill('New draft during response');await p.evaluate(()=>testHost.submits.shift()());await p.waitForTimeout(25);check('new draft survives old request acknowledgment',await p.locator('#prompt').inputValue()==='New draft during response');await ctx.close()}
  {const {page:p,ctx}=await setup({noProvider:true});check('missing provider disables send',await p.locator('#submit').isDisabled());check('missing provider is not reported as connected',(await p.locator('#connection-status').textContent()).includes('Choose an AI'));await p.locator('#prompt').fill('Settings preserves this');await p.keyboard.press('Control+,');check('settings is an in-app modal',await p.locator('#settings-dialog').evaluate(n=>n.matches(':modal')));await p.keyboard.press('Escape');check('settings restores composer focus and text',await p.evaluate(()=>document.activeElement.id==='prompt')&&await p.locator('#prompt').inputValue()==='Settings preserves this');await p.locator('#open-settings').click();await p.locator('#provider-path').fill('/fixture/bin/claude');await p.locator('[data-provider="codex"]').focus();await p.keyboard.press('ArrowRight');await p.locator('#connect-provider').click();check('provider selection uses real existing configure handler',await p.evaluate(()=>testHost.calls.some(c=>c[0]==='configure'&&c[1].kind==='claude')));await p.screenshot({path:path.join(root,'integrated-settings.png')});await p.keyboard.press('Escape');for(const [width,height] of [[760,560],[390,844]]){await p.setViewportSize({width,height});check(`integrated layout has no horizontal overflow ${width}`,await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:path.join(root,`integrated-${width}.png`)})}await ctx.close()}
  {const {page:p,ctx}=await setup();await p.evaluate(()=>testHost.blockSave=true);await p.locator('#prompt').fill('First save');await p.waitForTimeout(210);await p.locator('#prompt').fill('Latest save');await p.waitForTimeout(210);check('per-conversation saves do not overtake each other',await p.evaluate(()=>testHost.saves.length===1));await p.evaluate(()=>{testHost.blockSave=false;testHost.saves.shift()()});await p.waitForTimeout(30);check('serialized saves retain newest stored text',await p.evaluate(()=>testHost.state.conversations[0].draft==='Latest save'));await ctx.close()}
  {const {page:p,ctx}=await setup();await p.locator('#prompt').fill('First request');await p.locator('#submit').click();await p.waitForTimeout(20);await p.evaluate(()=>{const s=testHost.state,r=s.runs[0];r.answer='Original conversation answer';r.status='completed';r.updatedAt='2099';const later=structuredClone(r);later.id='later';later.admitted.requestID='later';later.status='failed';later.error='Later request failed';later.updatedAt='1900';s.runs.push(later)});await tick(p);check('run controls follow admission order instead of completion timestamp',await p.locator('#retry-run').isVisible()&&(await p.locator('#retry-run').getAttribute('data-run-id'))==='later');await p.evaluate(()=>{const broken=structuredClone(testHost.state.runs[0]);broken.id='broken';broken.conversationID='c2';testHost.state.runs.push(broken)});await p.locator('#conversations button').nth(1).click();check('invalid destination history cannot show previous conversation as current',await p.locator('#transcript').isHidden()&&await p.locator('#submit').isDisabled()&&await p.locator('#retry-run').isHidden()&&(await p.locator('#connection-status').textContent()).includes('couldn’t read'));await ctx.close()}
  {const {page:p,ctx}=await setup();await p.evaluate(()=>{testHost.snapshotDelay=900;testHost.state.selectedProviderID=null;window.__polls.forEach(f=>f())});await p.waitForTimeout(760);await p.evaluate(()=>{testHost.state.selectedProviderID='fixture:local';window.__polls.forEach(f=>f())});await p.waitForTimeout(190);check('snapshot latency exceeding polling interval does not starve results',await p.locator('#submit').isDisabled());await p.waitForTimeout(760);check('later delayed snapshot still advances connection state',!(await p.locator('#submit').isDisabled()));await ctx.close()}
  check('no unhandled renderer errors',errors.length===0);
  fs.writeFileSync(path.join(root,'INTEGRATED_BROWSER.json'),JSON.stringify({scope:'Actual R2 web modules with synthetic host, no native app/provider execution.',results,errors},null,2)+'\n');console.log(JSON.stringify({checks:results.length,errors}));
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
