import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {parseArtifactRequest,parseArtifactInspection,parseHostSnapshot} from './snapshot/prototypes/ai-native-workspace/src/host/contracts.ts';
import {createTauriWorkspaceAdapter} from './snapshot/prototypes/ai-native-workspace/src/host/tauriAdapter.ts';
const hash=s=>createHash('sha256').update(s).digest('hex');const text='Exact 🪐 é\n<script>literal</script>';
const q={artifactID:'artifact-a',conversationID:'chat-a',requestID:'run-a',expectedSHA256:hash(text)};
const reply=(txt=text)=>({schemaVersion:1,artifactID:q.artifactID,conversationID:q.conversationID,requestID:q.requestID,previewKind:'plainText',languageHint:null,byteLength:Buffer.byteLength(txt),contentSHA256:hash(txt),availability:'available',text:txt});
const summary=()=>({schemaVersion:1,artifactID:q.artifactID,conversationID:q.conversationID,requestID:q.requestID,origin:{kind:'finalAnswer',memberID:null,providerID:'codex'},displayName:'Final answer',previewKind:'plainText',languageHint:null,byteLength:Buffer.byteLength(text),contentSHA256:hash(text),availability:'available',createdAt:'2026-09-10',supersedesArtifactID:null});
function snapshot(){const provider={id:'codex',kind:'codex',executablePath:'/synthetic/codex',model:null,timeoutMs:60000};return {schemaVersion:1,activeConversationID:'chat-a',selectedProviderID:'codex',providers:[provider],conversations:['chat-a','chat-b'].map(id=>({id,title:id,readOnly:false,draft:'',richDraft:{schemaVersion:1,revision:0,attachmentIDs:[],selection:null,team:null}})),runs:[{id:'run-a',conversationID:'chat-a',status:'completed',updatedAt:'now',admitted:{requestID:'run-a',conversationID:'chat-a',prompt:'Synthetic',mode:'direct',provider,retryOf:null},answer:text,error:null}],artifacts:[summary()]};}
test('exact unicode inspection and metadata parse without private output',async()=>{assert.equal((await parseArtifactInspection(reply(),q)).text,text);const s=parseHostSnapshot(snapshot()).artifacts[0];assert.deepEqual(s,summary());assert.equal('text'in s,false);});
for(const field of ['artifactID','conversationID','requestID','contentSHA256'])test(`inspection rejects mismatched ${field}`,async()=>{await assert.rejects(parseArtifactInspection({...reply(),[field]:field==='contentSHA256'?'0'.repeat(64):'other'},q));});
for(const [field,value] of [['schemaVersion',2],['byteLength',text.length],['byteLength',-1],['byteLength',1.5],['text',text+'tampered'],['previewKind','html'],['languageHint','javascript'],['availability','corrupt'],['text','x'.repeat(2*1024*1024+1)]])test(`invalid inspection ${field} ${typeof value==='string'?value.slice(0,18):value}`,async()=>{await assert.rejects(parseArtifactInspection({...reply(),[field]:value},q));});
for(const field of ['storage','sourcePath','relativeKey','invocationID','attemptID','approvedContext'])test(`reject enumerable private ${field}`,async()=>{await assert.rejects(parseArtifactInspection({...reply(),[field]:'private'},q));const s=snapshot();s.artifacts[0][field]='private';assert.throws(()=>parseHostSnapshot(s));});
for(const kind of ['duplicate','conversation','request','provider','forward','cycle','origin','member','version'])test(`summary rejects ${kind}`,()=>{const s=snapshot(),a=s.artifacts[0];if(kind==='duplicate')s.artifacts.push(structuredClone(a));if(kind==='conversation')a.conversationID='chat-b';if(kind==='request')a.requestID='absent';if(kind==='provider')a.origin.providerID='other';if(kind==='forward'||kind==='cycle')a.supersedesArtifactID=kind==='cycle'?a.artifactID:'future';if(kind==='origin')a.origin.invocationID='private';if(kind==='member'){a.origin.kind='memberAnswer';a.origin.memberID='member-1';a.displayName='member-1 answer';}if(kind==='version')a.schemaVersion=2;assert.throws(()=>parseHostSnapshot(s));});
test('request accepts only bounded ASCII exact plain data fields without getters',()=>{for(const v of [{...q,path:'/tmp/x'},{...q,artifactID:'../x'},{...q,artifactID:'🪐'},{...q,artifactID:'x'.repeat(129)},{...q,expectedSHA256:q.expectedSHA256.toUpperCase()},Object.create(q)])assert.throws(()=>parseArtifactRequest(v));let reads=0;const v={...q};Object.defineProperty(v,'artifactID',{enumerable:true,get(){reads++;return 'x';}});assert.throws(()=>parseArtifactRequest(v));assert.equal(reads,0);});
test('DEFECT: bridge can rewrite its shared request and accepted response identity',async()=>{const bridge=Object.fromEntries(['getSnapshot','getModelCatalog','createConversation','openConversation','saveRichDraft','submitRun','reconcileRun','cancelRun','onRunEvent'].map(k=>[k,async()=>{}]));bridge.inspectArtifact=async request=>{request.conversationID='chat-b';request.requestID='run-b';request.artifactID='artifact-b';return {...reply(),conversationID:'chat-b',requestID:'run-b',artifactID:'artifact-b'};};const a=createTauriWorkspaceAdapter(bridge);const result=await a.inspectArtifact(q);assert.equal(result.conversationID,'chat-b');assert.equal(q.conversationID,'chat-a');});
test('DEFECT: lone surrogate is accepted using replacement-byte digest',async()=>{const invalid='\ud800';const result=await parseArtifactInspection(reply(invalid),{...q,expectedSHA256:hash(invalid)});assert.equal(result.text,invalid);assert.equal(result.byteLength,3);});
