const {chromium}=require('/Users/Aaravshah/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs');const out='/Users/Aaravshah/Documents/ChatGPT/App for me to integrate all my AI/qa-artifacts/pages-presentation-candidate-20260907-v3/independent-evidence';
(async()=>{
const browser=await chromium.launch({headless:true,executablePath:'/Users/Aaravshah/Library/Caches/ms-playwright/chromium_headless_shell-1223/chrome-headless-shell-mac-arm64/chrome-headless-shell'});
try{
const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1});await context.route('**/*',route=>new URL(route.request().url()).hostname==='127.0.0.1'?route.continue():route.abort());
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',msg=>{if(['error','warning'].includes(msg.type()))errors.push(msg.type()+': '+msg.text());});
const base='http://127.0.0.1:4270/rivune/';const result={engine:browser.version(),base,viewport:{width:390,height:844},errors,menu:{}};
async function settle(){await page.waitForFunction(()=>{const el=document.querySelector(location.hash);return el&&Math.abs(el.getBoundingClientRect().top-parseFloat(getComputedStyle(document.documentElement).scrollPaddingTop))<3;});}
await page.goto(base);await page.locator('summary').click();await page.getByRole('navigation',{name:'Mobile navigation',exact:true}).getByRole('link',{name:'The app',exact:true}).click();await settle();
result.menu.pointer={hash:new URL(page.url()).hash,open:await page.locator('.mobile-menu').evaluate(e=>e.open)};await page.screenshot({path:out+'/pointer-product.png'});
await page.goto(base);await page.locator('summary').focus();await page.keyboard.press('Enter');await page.keyboard.press('Tab');result.menu.keyboardFirstFocus=await page.locator(':focus').innerText();await page.keyboard.press('Enter');await settle();result.menu.keyboard={hash:new URL(page.url()).hash,open:await page.locator('.mobile-menu').evaluate(e=>e.open)};await page.screenshot({path:out+'/keyboard-product.png'});
const link=page.getByRole('link',{name:'View larger image',exact:true});await link.focus();result.enlargement=await link.evaluate(e=>({text:e.innerText,href:e.getAttribute('href'),target:e.target,rel:e.rel,width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height,focus:document.activeElement===e}));await page.screenshot({path:out+'/image-link-focused.png'});
const popupWait=page.waitForEvent('popup');await page.keyboard.press('Enter');const popup=await popupWait;await popup.waitForLoadState('load');result.enlargement.opened={url:popup.url(),...await popup.evaluate(()=>({openerIsNull:window.opener===null,images:[...document.images].map(i=>({complete:i.complete,width:i.naturalWidth,height:i.naturalHeight}))}))};await popup.screenshot({path:out+'/enlarged-image.png'});result.enlargement.viewerBefore=await popup.locator('img').evaluate(e=>({width:e.getBoundingClientRect().width,cursor:getComputedStyle(e).cursor}));await popup.locator('img').click();result.enlargement.viewerAfter=await popup.locator('img').evaluate(e=>({width:e.getBoundingClientRect().width,cursor:getComputedStyle(e).cursor}));await popup.screenshot({path:out+'/full-resolution-image-view.png'});await popup.close();
await page.setViewportSize({width:320,height:568});await page.goto(base+'#product');await settle();await link.scrollIntoViewIfNeeded();result.smallViewport={width:320,height:568,...await page.evaluate(()=>({documentWidth:document.documentElement.scrollWidth,viewportWidth:document.documentElement.clientWidth,linkWidth:document.querySelector('.product-image-zoom').getBoundingClientRect().width,linkHeight:document.querySelector('.product-image-zoom').getBoundingClientRect().height}))};await page.screenshot({path:out+'/small-mobile-image-link.png'});
fs.writeFileSync(out+'/focused-observations.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));
if(result.menu.pointer.open||result.menu.keyboard.open||result.menu.pointer.hash!=='#product'||result.menu.keyboard.hash!=='#product'||result.enlargement.height<44||!result.enlargement.opened.openerIsNull||result.smallViewport.documentWidth>result.smallViewport.viewportWidth||errors.length)throw Error('Focused acceptance check failed');
}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
