const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {chromium}=require('/Users/Aaravshah/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const web=path.resolve(__dirname,'../../cross-platform-shell-20260907/candidate4-runtime-r2/web');
(async()=>{const browser=await chromium.launch({executablePath:'/Users/Aaravshah/Library/Caches/ms-playwright/chromium_headless_shell-1223/chrome-headless-shell-mac-arm64/chrome-headless-shell',headless:true});const checks=[],errors=[];const check=(s,b)=>{assert.ok(b,s);checks.push(s)};
try{const ctx=await browser.newContext({viewport:{width:1120,height:800},reducedMotion:'reduce'});await ctx.route('**/*',async r=>{const u=new URL(r.request().url());if(u.origin!=='https://rivune-layout.test')return r.abort();const f=path.resolve(web,'.'+(u.pathname==='/'?'/index.html':u.pathname));if(!f.startsWith(web+path.sep)||!fs.existsSync(f))return r.abort();await r.fulfill({body:fs.readFileSync(f),contentType:({'.mjs':'text/javascript','.css':'text/css','.html':'text/html','.png':'image/png','.svg':'image/svg+xml'})[path.extname(f)]||'text/plain'})});
const p=await ctx.newPage();p.on('pageerror',e=>errors.push(String(e)));await p.goto('https://rivune-layout.test/');await p.locator('#open-settings').waitFor();await p.evaluate(()=>document.querySelector('#onboarding-dialog').close());
for(const zoom of [1,1.25,1.5]){await p.evaluate(z=>document.body.style.zoom=z,zoom);for(const kind of ['settings','onboarding']){
if(kind==='settings')await p.locator('#open-settings').click();else await p.evaluate(()=>document.querySelector('#onboarding-dialog').showModal());
const b=p.locator('#close-'+kind);check('Centered '+kind+' '+zoom,await b.evaluate(n=>{const a=n.getBoundingClientRect(),s=n.querySelector('svg').getBoundingClientRect();return Math.abs((a.left+a.right-s.left-s.right)/2)<.6&&Math.abs((a.top+a.bottom-s.top-s.bottom)/2)<.6}));check('Label hit area '+kind+' '+zoom,await b.evaluate(n=>n.getAttribute('aria-label').startsWith('Close ')&&n.getBoundingClientRect().width>=32));await b.focus();await p.keyboard.press('Tab');await p.keyboard.press('Shift+Tab');check('Keyboard focus '+kind+' '+zoom,await b.evaluate(n=>getComputedStyle(n).outlineStyle!=='none'));if(zoom===1)await b.screenshot({path:path.join(__dirname,kind+'-close.png')});await p.keyboard.press('Escape');check('Escape closes '+kind+' '+zoom,await p.locator('#'+kind+'-dialog').evaluate(n=>!n.open));}}
check('No browser errors',errors.length===0);fs.writeFileSync(path.join(__dirname,'CLOSE_CHECKS.json'),JSON.stringify({checks,errors,scope:'Actual canonical controls at three browser scales, native verification pending'},null,2));console.log(JSON.stringify({passed:checks.length}));}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
